window.MADAR_DATA = {
  learningModules: [
    {id:"foundations", n:"01", title:"زبان فضا و تصویر کلان مأموریت", en:"Space Mission Foundations", level:"مقدماتی", time:"۳ ساعت", lessons:6, prereq:"بدون پیش‌نیاز", icon:"◎", desc:"از مسئله مأموریت تا بخش زمینی؛ تمایز ماهواره، فضاپیما، محموله و پرتابگر.", outcomes:["ترسیم معماری یک مأموریت","تشخیص فازهای چرخه عمر","خواندن واژگان اصلی منابع انگلیسی"]},
    {id:"orbits", n:"02", title:"مکانیک مداری پایه", en:"Orbital Mechanics I", level:"دانشگاهی", time:"۸ ساعت", lessons:10, prereq:"فیزیک ۱ و حسابان", icon:"◉", desc:"مسئله دو جسم، مقاطع مخروطی، عناصر کلاسیک مدار و مانورهای انتقالی.", outcomes:["محاسبه سرعت و دوره مدار","تفسیر شش عنصر مداری","حل انتقال هوهمن"]},
    {id:"propulsion", n:"03", title:"پیشرانش و معادله موشک", en:"Rocket Propulsion", level:"دانشگاهی", time:"۷ ساعت", lessons:9, prereq:"ترمودینامیک مقدماتی", icon:"⇧", desc:"رانش، تکانه ویژه، نسبت جرمی، موتورهای مایع و جامد و چرخه‌های متداول.", outcomes:["استفاده از معادله تسیولکوفسکی","مقایسه LOX/RP-1 و LOX/LH2","تحلیل مقدماتی مرحله‌بندی"]},
    {id:"ascent", n:"04", title:"مسیر صعود و تزریق مداری", en:"Ascent & Orbit Insertion", level:"پیشرفته", time:"۶ ساعت", lessons:8, prereq:"ماژول ۲ و ۳", icon:"⌁", desc:"پنجره پرتاب، گردش گرانشی، Max-Q، قیود مسیر و تزریق مستقیم یا پارکینگ.", outcomes:["شرح کامل توالی پرتاب","تفکیک اتلاف‌های دلتاوی","تحلیل رویدادهای تله‌متری"]},
    {id:"spacecraft", n:"05", title:"زیرسامانه‌های ماهواره", en:"Spacecraft Subsystems", level:"دانشگاهی", time:"۱۰ ساعت", lessons:12, prereq:"ماژول ۱", icon:"◇", desc:"سازه، توان، حرارت، مخابرات، C&DH، کنترل وضعیت، پیشرانش و محموله.", outcomes:["ساخت بودجه جرم و توان","تعریف رابط زیرسامانه‌ها","انتخاب معماری اولیه CubeSat"]},
    {id:"gnc", n:"06", title:"هدایت، ناوبری و کنترل", en:"GNC & ADCS", level:"پیشرفته", time:"۹ ساعت", lessons:11, prereq:"کنترل و جبر خطی", icon:"⌖", desc:"تخمین حالت، حسگرهای نگرش، عملگرها و حلقه کنترل وضعیت و مدار.", outcomes:["تمایز Guidance و Navigation","مدل‌کردن دینامیک نگرش","شناخت فیلتر کالمن"]},
    {id:"mission-design", n:"07", title:"طراحی و تحلیل مأموریت", en:"Mission Analysis", level:"پیشرفته", time:"۸ ساعت", lessons:9, prereq:"مکانیک مداری پایه", icon:"△", desc:"نیازمندی پوشش، تکرار زمینی، بودجه دلتاوی، دسترسی ایستگاه و انتخاب مدار.", outcomes:["تبدیل هدف علمی به مدار","ساخت Concept of Operations","انجام Trade Study"]},
    {id:"comms", n:"08", title:"مخابرات و بخش زمینی", en:"TT&C and Ground Segment", level:"دانشگاهی", time:"۶ ساعت", lessons:7, prereq:"مدار و سیگنال مقدماتی", icon:"⌁", desc:"Link Budget، آنتن، باندهای فرکانسی، گذر زمینی و شبکه ایستگاه‌ها.", outcomes:["محاسبه لینک بودجه ساده","پیش‌بینی پنجره تماس","تشخیص TT&C از Payload Data"]},
    {id:"environment", n:"09", title:"محیط فضا، توان و حرارت", en:"Space Environment", level:"دانشگاهی", time:"۷ ساعت", lessons:8, prereq:"انتقال حرارت مقدماتی", icon:"☼", desc:"تابش، پلاسما، اکسیژن اتمی، سیکل حرارتی، سلول خورشیدی و باتری.", outcomes:["ساخت بودجه انرژی مداری","شناخت حالات حرارتی","انتخاب راهکار تاب‌آوری پرتویی"]},
    {id:"systems", n:"10", title:"مهندسی سیستم‌های فضایی", en:"Space Systems Engineering", level:"دانشگاهی", time:"۸ ساعت", lessons:10, prereq:"ماژول ۱ و ۵", icon:"▦", desc:"نیازمندی، رابط، ریسک، V&V، بازبینی‌های SRR/PDR/CDR و چرخه عمر ناسا.", outcomes:["نوشتن نیازمندی قابل راستی‌آزمایی","ساخت ماتریس ردیابی","برنامه‌ریزی Verification"]},
    {id:"operations", n:"11", title:"عملیات اولیه و بهره‌برداری", en:"LEOP & Operations", level:"پیشرفته", time:"۵ ساعت", lessons:7, prereq:"زیرسامانه‌ها و مخابرات", icon:"◌", desc:"First Acquisition، راه‌اندازی، Safe Mode، نگهداری مدار و پایان مأموریت.", outcomes:["طراحی رویه LEOP","تعریف FDIR","برنامه دفع پایان عمر"]},
    {id:"failures", n:"12", title:"تحلیل شکست و درس‌آموخته‌ها", en:"Failure Analysis", level:"پیشرفته", time:"۶ ساعت", lessons:8, prereq:"پیشرانش و مهندسی سیستم", icon:"!", desc:"Fault Tree، FMEA، علت نزدیک و ریشه‌ای، عوامل سازمانی و اقدامات اصلاحی.", outcomes:["تفکیک علت از نشانه","خواندن گزارش هیئت بررسی","ساخت زنجیره درس‌آموخته"]}
  ],

  launchStages: [
    {id:0, time:"T−ماه‌ها تا ساعت‌ها", title:"طراحی مأموریت و کارزار پرتاب", en:"Mission Design & Launch Campaign", altitude:"۰ km", speed:"۰", tag:"پیش از پرتاب", summary:"مدار هدف، جرم محموله، پنجره زمانی و پرتابگر با هم سازگار می‌شوند.", physics:"میل مدار با عرض جغرافیایی پایگاه و آزیموت پرتاب پیوند دارد. تغییر صفحه مداری پرهزینه است؛ بنابراین انتخاب پایگاه از ابتدا بخشی از بودجه دلتاوی است.", events:["تحلیل بارهای کوپل‌شده","آزمون ارتعاش و آکوستیک","سوخت‌گیری و Encapsulation","Flight Readiness Review"], risk:"خطای رابط مکانیکی/الکتریکی، آلودگی محموله، ناسازگاری نرم‌افزار زمینی", telemetry:"Continuity، فشار مخزن، دما، وضعیت باتری و شبکه فرمان"},
    {id:1, time:"T−۱۰ min تا T0", title:"شمارش نهایی و روشن‌شدن", en:"Terminal Count & Ignition", altitude:"۰ km", speed:"۰", tag:"T0", summary:"رایانه پرواز کنترل را تحویل می‌گیرد؛ مخازن تحت فشار و موتورها وارد توالی روشن‌شدن می‌شوند.", physics:"برای موتور مایع، پایدارشدن احتراق و رسیدن رانش به آستانه آزادسازی ضروری است. موتور جامد پس از روشن‌شدن عموماً خاموش‌پذیر نیست.", events:["انتقال به برق داخلی","Arm شدن سامانه ایمنی پرواز","Ignition Sequence Start","رهاسازی Hold-down"], risk:"Hard start، ناپایداری احتراق، خاموشی موتور یا آزادسازی نامتقارن", telemetry:"فشار محفظه، دور توربوپمپ، Thrust OK، نرخ‌های ژیروسکوپ"},
    {id:2, time:"T+۰ تا ۷۰ s", title:"برخاست و پیچ/غلت برنامه‌ریزی‌شده", en:"Liftoff, Pitch & Roll", altitude:"۰–۲۰ km", speed:"۰–۱.۵ km/s", tag:"جو غلیظ", summary:"موشک از برج فاصله می‌گیرد، صفحه پرواز را تنظیم می‌کند و گردش گرانشی را آغاز می‌کند.", physics:"رانش باید از وزن بیشتر باشد. حرکت اولیه نزدیک عمودی، پاک‌کردن برج و کاهش بار جانبی را ممکن می‌کند؛ سپس مسیر برای ساخت سرعت افقی خم می‌شود.", events:["Tower Clear","Pitch-over","Roll Program","شروع Gravity Turn"], risk:"برخورد با برج، باد برشی، خطای TVC، ناپایداری آئروالاستیک", telemetry:"شتاب، زاویه حمله، فرمان گیمبال، بارهای سازه‌ای"},
    {id:3, time:"تقریباً T+۶۰ تا ۹۰ s", title:"بیشینه فشار دینامیکی", en:"Maximum Dynamic Pressure — Max Q", altitude:"۱۰–۱۵ km", speed:"≈ ماخ ۱–۲", tag:"Max Q", summary:"ترکیب سرعت رو‌به‌افزایش و چگالی رو‌به‌کاهش، فشار دینامیکی را به بیشینه می‌رساند.", physics:"q = ½ρv². موتور ممکن است Throttle Down کند تا حاصل بار آیرودینامیکی، زاویه حمله و پاسخ سازه از حدود مجاز نگذرد.", events:["Throttle Bucket","عبور از سرعت صوت","Peak Aero Load","Throttle Up"], risk:"کمانش پوسته، Flutter، بار جانبی و شکست فیرینگ", telemetry:"q برآوردی، شتاب جانبی، فشار سطح، مودهای ارتعاشی"},
    {id:4, time:"T+۲ تا ۳ min", title:"خاموشی و جدایش مرحله اول", en:"MECO & Stage Separation", altitude:"۶۰–۹۰ km", speed:"۲–۳ km/s", tag:"Staging", summary:"پس از مصرف پیشرانه، مرحله سنگینِ خالی جدا و مرحله بعد برای ادامه شتاب روشن می‌شود.", physics:"مرحله‌بندی جرم خشک را حذف می‌کند و نسبت جرمی مؤثر را بهبود می‌دهد. جدایش باید با فاصله و نرخ زاویه‌ای کنترل‌شده رخ دهد تا Recontact ایجاد نشود.", events:["MECO/BECO","فرمان‌های Pyro یا Pneumatic","Stage Separation","Second-stage Ignition"], risk:"روشن‌نشدن مرحله بالا، برخورد مجدد، نشتی یا حرکت زاویه‌ای زیاد", telemetry:"شتاب طولی، Separation Switch، فشار ورودی موتور، وضعیت Igniter"},
    {id:5, time:"T+۳ تا ۴ min", title:"رهاسازی فیرینگ", en:"Payload Fairing Jettison", altitude:"بیش از ۱۰۰ km", speed:"۳–۴ km/s", tag:"خروج از جو", summary:"وقتی شار حرارتی و فشار آیرودینامیکی کم شد، پوشش محموله دیگر لازم نیست و دور انداخته می‌شود.", physics:"جدایش زودهنگام محموله را در معرض گرمایش و آکوستیک قرار می‌دهد؛ جدایش دیرهنگام جرم مرده را حمل می‌کند و عملکرد را کاهش می‌دهد.", events:["شرط ارتفاع/شار حرارتی","بازشدن خط جدایش","دورشدن نیم‌پوسته‌ها","بررسی Fairing Gone"], risk:"جدایش ناقص، تماس با محموله، شوک پیروتکنیکی", telemetry:"میکروسوئیچ جدایش، شتاب شوک، تصویر دوربین، دمای محموله"},
    {id:6, time:"T+۸ تا ۱۲ min", title:"خاموشی مرحله بالا و مدار پارکینگ", en:"SECO & Parking Orbit", altitude:"۱۶۰–۳۰۰ km", speed:"≈۷.۸ km/s", tag:"مدار اولیه", summary:"مرحله بالا به سرعت تقریباً افقیِ کافی می‌رسد؛ وسیله اکنون پیوسته در سقوط آزاد پیرامون زمین است.", physics:"ارتفاع به‌تنهایی مدار نمی‌سازد. شرط اصلی، سرعت مماسی مناسب است. برای مدار دایروی v=√(μ/r) و در ۲۰۰ km حدود ۷.۸ km/s است.", events:["Second Engine Cutoff","Coast Phase","تعیین مدار ناوبری","اصلاح خطای تزریق"], risk:"کمبود سرعت، حضیض درون جو، خاموشی زودهنگام یا خطای ناوبری", telemetry:"بردار حالت، باقیمانده دلتاوی، نسبت مخلوط، خطای Guidance"},
    {id:7, time:"T+۲۰ min تا چند ساعت", title:"روشن‌شدن مجدد و انتقال", en:"Restart & Transfer", altitude:"وابسته به مأموریت", speed:"متغیر", tag:"مانور مداری", summary:"مرحله بالا در نقطه هدف دوباره روشن می‌شود تا اوج/حضیض، میل یا انرژی فرار را تغییر دهد.", physics:"زمان و جهت Burn تعیین می‌کند کدام عنصر مداری تغییر کند. Burn مماسی در حضیض، اوج را مؤثرتر بالا می‌برد؛ تغییر صفحه در سرعت کمتر ارزان‌تر است.", events:["Ullage/Settling","Engine Restart","SECO-2","Spin-up در برخی مأموریت‌ها"], risk:"ته‌نشینی‌نکردن سوخت، روشن‌نشدن، خطای زمان‌بندی یا احتراق طولانی", telemetry:"وضعیت Propellant Settling، فشار محفظه، تخمین مدار جدید"},
    {id:8, time:"T+۱۰ min تا چند ساعت", title:"جدایش ماهواره", en:"Payload Deployment", altitude:"مدار تزریق", speed:"مداری", tag:"Deployment", summary:"سامانه جدایش، ماهواره را با سرعت نسبی کوچک و وضعیت تعریف‌شده از مرحله بالا دور می‌کند.", physics:"فنر یا مکانیزم جدایش سرعتی در حد متر بر ثانیه می‌دهد. توالی چندمحموله‌ای باید از برخورد و تداخل رادیویی جلوگیری کند.", events:["Safe & Arm","فرمان جدایش","Separation Confirmation","Collision Avoidance"], risk:"گیرکردن مکانیزم، نرخ زاویه‌ای زیاد، برخورد میان محموله‌ها", telemetry:"سوئیچ جدایش، دوربین، تغییر اینرسی مرحله، Beacon ماهواره"},
    {id:9, time:"T+دقایق تا هفته‌ها", title:"LEOP، نخستین تماس و راه‌اندازی", en:"Early Orbit & Commissioning", altitude:"مدار عملیاتی", speed:"مداری", tag:"عملیات", summary:"ماهواره زنده‌بودن خود را اعلام می‌کند، پنل‌ها را باز می‌کند و مرحله‌به‌مرحله وارد حالت عملیاتی می‌شود.", physics:"توان مثبت و پایداری حرارتی اولویت دارند. تخمین مدار دقیق‌تر، Detumble، کسب خورشید و مانورهای اصلاحی پیش از روشن‌کردن محموله انجام می‌شوند.", events:["First Acquisition of Signal","Solar Array Deployment","Detumble & Sun Acquisition","Payload Commissioning"], risk:"No Contact، توان منفی، قفل‌نشدن نگرش، بازنشدن پنل یا آنتن", telemetry:"ولتاژ/جریان، نرخ زاویه‌ای، دما، حالت FDIR، کیفیت لینک"}
  ],

  orbits: [
    {id:"leo", name:"مدار پایین زمین", en:"Low Earth Orbit — LEO", range:"حدود ۱۸۰ تا ۲٬۰۰۰ km", period:"≈ ۸۸ تا ۱۲۷ دقیقه", color:"#6ee7c7", examples:"ISS، Starlink، Sentinel، ماهواره‌های سنجشی", uses:["تصویربرداری با تفکیک بالا","اینترنت کم‌تأخیر","ایستگاه فضایی و پژوهش","هواشناسی قطبی"], pros:["انرژی و هزینه پرتاب کمتر","تأخیر مخابراتی پایین","قدرت/دهانه کمتر برای تصویر مشابه"], cons:["پوشش لحظه‌ای محدود","Drag و افت مدار در ارتفاع پایین","نیاز به منظومه یا شبکه زمینی"]},
    {id:"sso", name:"مدار خورشیدآهنگ", en:"Sun-Synchronous Orbit — SSO", range:"معمولاً ۵۰۰ تا ۸۰۰ km", period:"≈ ۹۵ تا ۱۰۱ دقیقه", color:"#9be15d", examples:"Landsat، Sentinel-2، SPOT", uses:["سنجش‌ازدور","نقشه‌برداری و کشاورزی","پایش اقلیم و یخ","شناسایی"], pros:["نور خورشید تقریباً ثابت در هر گذر","مقایسه‌پذیری بهتر تصاویر زمانی","پوشش جهانی با مدار نزدیک قطبی"], cons:["میل رتروگراد حدود ۹۷–۹۸ درجه","تراکم ترافیک نزدیک قطب‌ها","پنجره پرتاب محدودتر"]},
    {id:"meo", name:"مدار میانی زمین", en:"Medium Earth Orbit — MEO", range:"۲٬۰۰۰ تا زیر ۳۵٬۷۸۶ km", period:"≈ ۲ تا کمتر از ۲۴ ساعت", color:"#5cc8ff", examples:"GPS، Galileo، GLONASS، BeiDou MEO", uses:["ناوبری و زمان‌سنجی","مخابرات پهن‌باند MEO","پژوهش محیط تابشی"], pros:["پوشش وسیع‌تر از LEO","تعداد ماهواره کمتر برای پوشش جهانی","Drag ناچیز"], cons:["عبور از کمربندهای وان‌آلن","تأخیر و توان لینک بیشتر از LEO","دسترسی و سرویس دشوارتر"]},
    {id:"geo", name:"مدار زمین‌آهنگ/زمین‌ایستا", en:"GSO / Geostationary Orbit — GEO", range:"۳۵٬۷۸۶ km بالای استوا", period:"۲۳h ۵۶m ۴s", color:"#ffc857", examples:"GOES، Meteosat، Intelsat، EDRS", uses:["تلویزیون و مخابرات ثابت","پایش پیوسته هواشناسی","رله داده","هشدار موشکی"], pros:["پوشش پیوسته یک ناحیه","آنتن زمینی ثابت","پوشش بزرگ با ماهواره کم"], cons:["تأخیر رفت‌وبرگشت زیاد","هزینه پرتاب و توان لینک بالا","پوشش ضعیف عرض‌های قطبی"]},
    {id:"gto", name:"مدار انتقال زمین‌ایستا", en:"Geostationary Transfer Orbit — GTO", range:"تقریباً ۲۰۰ × ۳۵٬۷۸۶ km", period:"≈ ۱۰.۵ ساعت", color:"#ff8b7b", examples:"مدار تحویل بسیاری از ماهواره‌های مخابراتی", uses:["انتقال انرژی‌کارا به GEO","تحویل مشترک محموله","آزمون مرحله بالایی"], pros:["کاهش نیاز پرتابگر به تزریق مستقیم GEO","انعطاف در زمان دایروی‌سازی"], cons:["نیاز ماهواره به موتور اوج","عبور چندباره از محیط تابشی","مصرف پیشرانه و کاهش عمر/جرم مفید"]},
    {id:"heo", name:"مدار بسیار بیضوی", en:"Highly Elliptical Orbit — HEO", range:"حضیض پایین، اوج ده‌ها هزار km", period:"اغلب ۱۲ یا ۲۴ ساعت", color:"#c6a6ff", examples:"Molniya، Tundra", uses:["مخابرات عرض‌های بالا","هشدار و پایش قطبی","علم مغناطیس‌سپهر"], pros:["زمان ماند طولانی نزدیک اوج","پوشش مناسب مناطق قطبی","هندسه مطلوب برای نیم‌کره هدف"], cons:["فاصله و سرعت بسیار متغیر","عبور از کمربند تابشی","پیچیدگی ردیابی و لینک"]}
  ],

  launchers: [
    {id:"falcon9", name:"Falcon 9 Block 5", maker:"SpaceX · ایالات متحده", status:"عملیاتی", height:"۷۰ m", diameter:"۳.۷ m", mass:"≈۵۴۹ t", stages:"۲", prop:"LOX / RP-1", leo:"۲۲٫۸ t (مصرفی)", gto:"۸٫۳ t (مصرفی)", reuse:"مرحله اول و فیرینگ", engines:"۹× Merlin 1D + ۱× Merlin Vacuum", note:"پرتابگر دومرحله‌ای با فرود پیشرانشی مرحله اول؛ ظرفیت واقعی وابسته به بازیابی و مدار هدف است.", source:"https://www.spacex.com/vehicles/falcon-9/"},
    {id:"electron", name:"Electron", maker:"Rocket Lab · آمریکا/نیوزیلند", status:"عملیاتی", height:"۱۸ m", diameter:"۱.۲ m", mass:"≈۱۳ t", stages:"۲ + Kick Stage اختیاری", prop:"LOX / Kerosene", leo:"≈۳۰۰ kg به SSO 500 km", gto:"—", reuse:"بازیابی مرحله اول در توسعه/آزمایش", engines:"۹× Rutherford + ۱× Rutherford Vacuum", note:"پرتابگر کوچک با پمپ الکتریکی؛ Kick Stage امکان تزریق دقیق و چندمحموله‌ای می‌دهد.", source:"https://www.rocketlabusa.com/launch/electron/"},
    {id:"ariane6", name:"Ariane 6 (A62/A64)", maker:"ArianeGroup / ESA · اروپا", status:"عملیاتی", height:"≈۶۲ m", diameter:"۵.۴ m", mass:"≈۵۳۰–۸۷۰ t", stages:"هسته + بالا + ۲/۴ بوستر", prop:"LOX/LH2 + بوستر جامد", leo:"تا ≈۲۱٫۶ t (A64)", gto:"تا ≈۱۱٫۵ t (A64)", reuse:"مصرفی", engines:"Vulcain 2.1 + Vinci restartable", note:"مرحله بالایی Vinci قابلیت روشن‌شدن مجدد دارد و برای تزریق چندمداره و دفع مرحله طراحی شده است.", source:"https://www.esa.int/Enabling_Support/Space_Transportation/Launch_vehicles/Ariane_6"},
    {id:"soyuz2", name:"Soyuz-2.1b / Fregat", maker:"Progress / Roscosmos · روسیه", status:"عملیاتی", height:"≈۴۶ m", diameter:"۱۰.۳ m با بوسترها", mass:"≈۳۱۲ t", stages:"۳ + Fregat اختیاری", prop:"LOX / Kerosene؛ Fregat هایپرگولیک", leo:"≈۸٫۲ t", gto:"وابسته به Fregat", reuse:"مصرفی", engines:"RD-107A/108A، RD-0124", note:"معماری تکامل‌یافته خانواده R-7؛ Fregat چندبار روشن می‌شود و برای تزریق‌های پیچیده مناسب است.", source:"https://www.esa.int/Enabling_Support/Space_Transportation/Launch_vehicles/Soyuz"},
    {id:"pslv", name:"PSLV-XL", maker:"ISRO · هند", status:"عملیاتی", height:"۴۴ m", diameter:"۲.۸ m هسته", mass:"≈۳۲۰ t", stages:"۴ + ۶ بوستر", prop:"جامد / مایع متناوب", leo:"≈۳٫۸ t", gto:"≈۱٫۴ t", reuse:"مصرفی", engines:"S139، Vikas، PS3، PS4", note:"پرتابگر چهارمرحله‌ای شناخته‌شده برای SSO؛ مرحله چهارم در برخی مأموریت‌ها سکوی آزمایش مداری می‌شود.", source:"https://www.isro.gov.in/PSLV_CON.html"},
    {id:"longmarch5", name:"Long March 5", maker:"CALT / CASC · چین", status:"عملیاتی", height:"≈۵۷ m", diameter:"۵ m هسته", mass:"≈۸۶۷ t", stages:"۲ + ۴ بوستر", prop:"LOX/LH2 هسته، LOX/Kerosene بوستر", leo:"≈۲۵ t", gto:"≈۱۴ t", reuse:"مصرفی", engines:"YF-77، YF-100، YF-75D", note:"پرتابگر سنگین برای ایستگاه فضایی، مأموریت‌های ماه و محموله‌های بزرگ GEO.", source:"http://www.cnsa.gov.cn/english/"}
  ],

  curatedFailures: [
    {date:"۲۰۲۶/۰۸/۱۰", iso:"2026-08-10", title:"Long March 7A · ChinaSat 4B", kind:"شکست پرتاب", phase:"صعود · حدود T+85s", severity:"از دست‌رفتن مأموریت", certainty:"تحقیق باز", cause:"رویداد غیرعادی و فروپاشی وسیله اندکی پس از پرتاب؛ علت فنی هنوز رسماً اعلام نشده است.", lesson:"تا انتشار گزارش رسمی، «آنچه دیده شد» را از «علت» جدا نگه دارید؛ ویدئو برای تعیین علت ریشه‌ای کافی نیست.", source:"https://www.cnn.com/2026/08/11/china/china-long-march-rocket-failure-intl-hnk", sourceName:"CNN / تأیید اولیه Xinhua"},
    {date:"۲۰۲۶/۰۵/۲۸", iso:"2026-05-28", title:"New Glenn · آزمون استاتیک NG-4", kind:"حادثه آزمایش زمینی", phase:"Static Fire", severity:"نابودی وسیله و آسیب سکوی 36", certainty:"تحقیق باز", cause:"انفجار روی سکو هنگام آزمون پیش از پرتاب؛ گزارش‌های اولیه به ناحیه سامانه پیشرانش اشاره داشتند، اما نتیجه نهایی باید از مرجع بررسی اخذ شود.", lesson:"آزمون یکپارچه خطر دارد، اما می‌تواند نقص را پیش از قرارگرفتن محموله عملیاتی و مسیر پروازی آشکار کند.", source:"https://spaceflightnow.com/2026/05/29/blue-origins-new-glenn-rocket-explodes-during-prelaunch-testing-at-cape-canaveral/", sourceName:"Spaceflight Now"},
    {date:"۲۰۲۶/۰۵/۲۲", iso:"2026-05-22", title:"Starship Flight 12 · Super Heavy", kind:"شکست بازیابی/آزمایشی", phase:"پس از جدایش", severity:"Hard splashdown بوستر", certainty:"تحقیق FAA", cause:"بوستر نتوانست همه موتورهای برنامه‌ریزی‌شده را برای Boostback روشن کند؛ بررسی رسمی برای عملکرد خارج از برنامه الزامی شد.", lesson:"موفقیت مرحله بالا، شکست هدف بازیابی را پاک نمی‌کند؛ معیار موفقیت باید پیش از مأموریت تعریف شود.", source:"https://spaceflightnow.com/2026/05/27/faa-requires-spacex-led-mishap-investigation-before-resumption-of-starship-launches/", sourceName:"FAA via Spaceflight Now"},
    {date:"۲۰۲۶/۰۴/۱۹", iso:"2026-04-19", title:"New Glenn 3 · BlueBird 7", kind:"شکست پرتاب", phase:"مرحله دوم", severity:"مدار ناکافی و بازورود محموله", certainty:"علت اعلام‌شده", cause:"یکی از دو موتور BE-3U رانش کافی تولید نکرد؛ گزارش بعدی بررسی، نشتی برودتی و یخ‌زدگی خط هیدرولیک را علت مستقیم دانست.", lesson:"زنجیره علت را از «کمبود رانش» تا مکانیزم فیزیکی و سپس کنترل فرایند/طراحی دنبال کنید.", source:"https://www.reuters.com/business/media-telecom/faa-orders-investigation-into-blue-origin-flight-mishap-2026-04-20/", sourceName:"Reuters / FAA"},
    {date:"۲۰۲۶/۰۴/۰۳", iso:"2026-04-03", title:"Tianlong-3 · پرواز نخست", kind:"شکست پرتاب", phase:"صعود · حدود ۳۳ ثانیه", severity:"از دست‌رفتن وسیله", certainty:"تحقیق باز", cause:"ناهنجاری قابل مشاهده در ناحیه موتور و پایان پرواز؛ شرکت اعلام کرد علت در دست تحلیل است.", lesson:"پرواز نخست ریسک Integration بالاتری دارد؛ داده زمینی موفق، محیط کوپل‌شده پرواز را کامل بازتولید نمی‌کند.", source:"https://spacenews.com/chinas-commercial-tianlong-3-rocket-fails-on-debut-launch/", sourceName:"SpaceNews"},
    {date:"۲۰۲۵/۱۲/۲۲", iso:"2025-12-22", title:"H3 · QZS-5", kind:"شکست پرتاب", phase:"روشن‌شدن دوم مرحله بالا", severity:"عدم تزریق به مدار برنامه‌ریزی‌شده", certainty:"بررسی فنی", cause:"روشن‌شدن دوم موتور LE-5B-3 به‌طور عادی آغاز نشد و زود خاموش شد.", lesson:"قابلیت Restart یک مأموریت مستقل در دل مأموریت است و باید شرایط حرارتی/سیالاتی Coast در Qualification پوشش داده شود.", source:"https://spaceflightnow.com/2025/12/22/h3-rocket-suffers-upper-stage-anomaly-fails-to-correctly-deploy-navigation-satellite/", sourceName:"JAXA via Spaceflight Now"},
    {date:"۲۰۲۵/۰۸/۱۵", iso:"2025-08-15", title:"Zhuque-2E Y3", kind:"شکست پرتاب", phase:"صعود", severity:"از دست‌رفتن مأموریت", certainty:"تحقیق اعلام‌شده", cause:"شرکت LandSpace وقوع anomaly را تأیید کرد و جزئیات علت در اعلام اولیه منتشر نشد.", lesson:"نبود اطلاعات عمومی به معنی امکان حدس قطعی نیست؛ برچسب «نامعلوم/در حال بررسی» بخشی از صداقت داده است.", source:"https://www.reuters.com/science/flight-test-chinese-start-up-landspaces-rocket-fails-2025-08-15/", sourceName:"Reuters"},
    {date:"۲۰۲۵/۰۵/۱۸", iso:"2025-05-18", title:"PSLV-C61 · EOS-09", kind:"شکست پرتاب", phase:"مرحله سوم", severity:"از دست‌رفتن ماهواره", certainty:"اعلام اولیه ISRO", cause:"دو مرحله نخست عادی بودند؛ در عملکرد موتور جامد مرحله سوم مشاهده غیرعادی ثبت شد و مأموریت کامل نشد.", lesson:"در موتور جامد امکان خاموش‌کردن یا تنظیم رانش محدود است؛ کیفیت ساخت و مدل Ballistics داخلی حیاتی‌اند.", source:"https://www.isro.gov.in/PSLV_C61_Mission.html", sourceName:"ISRO"},
    {date:"۲۰۲۵/۰۴/۲۹", iso:"2025-04-29", title:"Firefly Alpha FLTA006 · LM-400", kind:"شکست پرتاب", phase:"جدایش ۱/۲ و روشن‌شدن مرحله دوم", severity:"عدم دستیابی به سرعت مداری", certainty:"بررسی FAA/شرکت", cause:"رخداد هنگام جدایش به Extension نازل موتور مرحله دوم آسیب زد؛ موتور روشن ماند اما رانش برای مدار کافی نبود.", lesson:"جدایش مرحله یک رویداد چندفیزیکی است: دینامیک نسبی، plume، shock و تلرانس هندسی باید هم‌زمان تحلیل شوند.", source:"https://arstechnica.com/science/2025/04/fireflys-rocket-suffers-one-of-the-strangest-launch-failures-weve-ever-seen/", sourceName:"Firefly / Ars Technica"},
    {date:"۲۰۲۴/۱۱/۲۶", iso:"2024-11-26", title:"Epsilon S · آزمون موتور مرحله دوم", kind:"حادثه آزمایش زمینی", phase:"T+49s آزمون احتراق", severity:"انفجار موتور و آسیب تأسیسات", certainty:"هیئت بررسی JAXA", cause:"ناهنجاری احتراق در دومین کارزار آزمون؛ JAXA تیم بررسی رسمی تشکیل داد.", lesson:"تکرار anomaly پس از اقدام اصلاحی، نیاز به بازنگری فرضیات علت ریشه‌ای و پوشش آزمون را نشان می‌دهد.", source:"https://global.jaxa.jp/press/2024/11/20241127-1_e.html", sourceName:"JAXA"},
    {date:"۲۰۲۴/۰۶/۳۰", iso:"2024-06-30", title:"Tianlong-3 · Static Fire", kind:"حادثه آزمایش زمینی", phase:"آزمون مرحله اول", severity:"رهاشدن ناخواسته و انفجار", certainty:"علت اولیه شرکت", cause:"شکست سازه اتصال مرحله به سکوی آزمون باعث برخاست ناخواسته شد؛ رایانه موتورها را خاموش کرد و مرحله ۱.۵ km دورتر سقوط کرد.", lesson:"ظرفیت Hold-down باید با عدم‌قطعیت رانش، توزیع بار، Failure Mode و حاشیه سازه‌ای راستی‌آزمایی شود.", source:"https://www.reuters.com/technology/space/space-pioneer-says-part-rocket-crashed-central-china-during-test-2024-06-30/", sourceName:"Reuters / Space Pioneer"},
    {date:"۲۰۲۲/۱۲/۲۱", iso:"2022-12-21", title:"Vega-C VV22", kind:"شکست پرتاب", phase:"Zefiro 40 · T+151s", severity:"از دست‌رفتن دو ماهواره", certainty:"نتیجه هیئت مستقل", cause:"فرسایش گرما-مکانیکی غیرمنتظره Throat Insert کربن-کربن نازل و افت تدریجی فشار محفظه.", lesson:"گواهی ماده فقط با خواص اسمی کافی نیست؛ همگنی، معیار پذیرش و رفتار در هندسه واقعی باید پوشش داده شود.", source:"https://www.avio.com/press-release/conclusion-vv22-failure-investigation-independent-inquiry-commission-next-vega-flight", sourceName:"ESA/Arianespace IEC via Avio"}
  ],

  sources: [
    {name:"Launch Library 2", org:"The Space Devs", type:"داده زنده پرتاب", lang:"EN", trust:"تجمیع معتبر", url:"https://thespacedevs.com/llapi", note:"فهرست زمان‌مند پرتاب‌ها، وضعیت، پرتابگر، پایگاه، مدار و مأموریت؛ API نسخه 2.3."},
    {name:"GCAT", org:"Jonathan McDowell", type:"تاریخچه جامع", lang:"EN", trust:"داده پژوهشی", url:"https://planet4589.org/space/gcat/", note:"کاتالوگ اشیای مصنوعی، فهرست پرتاب‌ها، شکست‌های مداری و خانواده پرتابگرها؛ با مجوز CC-BY."},
    {name:"CelesTrak GP / OMM", org:"CelesTrak", type:"عناصر مداری", lang:"EN", trust:"مرجع فنی", url:"https://celestrak.org/NORAD/documentation/gp-data-formats.php", note:"داده‌های GP بر پایه USSF و قالب‌های OMM؛ برای داده جدید JSON/XML بر TLE پنج‌رقمی ترجیح داده شود."},
    {name:"Types of Orbits", org:"European Space Agency", type:"آموزش مدار", lang:"EN", trust:"رسمی", url:"https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits", note:"تعریف LEO، MEO، GEO، SSO، HEO، GTO و نقاط لاگرانژ."},
    {name:"NASA Systems Engineering Handbook", org:"NASA", type:"مهندسی سیستم", lang:"EN", trust:"رسمی", url:"https://www.nasa.gov/wp-content/uploads/2018/09/nasa_systems_engineering_handbook_0.pdf", note:"چرخه عمر، فرایندهای مهندسی سیستم، بازبینی‌ها، Verification و Validation."},
    {name:"NASA NTRS", org:"NASA", type:"گزارش و مقاله", lang:"EN", trust:"رسمی", url:"https://ntrs.nasa.gov/", note:"گزارش‌های فنی، مطالعات قابلیت اطمینان، شکست مأموریت و هندبوک‌ها."},
    {name:"Significant Incidents", org:"NASA SMA", type:"درس‌آموخته شکست", lang:"EN", trust:"رسمی", url:"https://sma.nasa.gov/SignificantIncidents/", note:"رخدادها و Close Callهای پرواز سرنشین‌دار بر اساس فاز مأموریت و منابع اصلی."},
    {name:"Space-Track.org", org:"US Space Force", type:"کاتالوگ و GP", lang:"EN", trust:"رسمی", url:"https://www.space-track.org/documentation", note:"SATCAT، GP/OMM، reentry و داده‌های SSA؛ نیازمند حساب و رعایت محدودیت درخواست."},
    {name:"FAA Commercial Space", org:"FAA", type:"مقررات و Mishap", lang:"EN", trust:"رسمی", url:"https://www.faa.gov/space", note:"مجوز پرتاب/بازورود و اطلاعیه‌های بررسی حوادث تجاری آمریکا."},
    {name:"JAXA Press Releases", org:"JAXA", type:"مأموریت و بررسی", lang:"EN/JA", trust:"رسمی", url:"https://global.jaxa.jp/press/", note:"اطلاعیه‌های پرتاب، نتایج اولیه anomaly و تشکیل هیئت‌های بررسی ژاپن."},
    {name:"ISRO Missions", org:"ISRO", type:"مأموریت و پرتابگر", lang:"EN", trust:"رسمی", url:"https://www.isro.gov.in/Missions.html", note:"صفحات رسمی PSLV/GSLV/LVM3 و مأموریت‌های هند."},
    {name:"پژوهشگاه فضایی ایران", org:"وزارت ارتباطات", type:"پروژه و پژوهش", lang:"FA", trust:"رسمی", url:"https://www.isrc.ac.ir/", note:"اطلاعات نهادی و پروژه‌های ماهواره، زیرسامانه و پژوهش فضایی ایران؛ برای هر ادعای فنی منبع اولیه جداگانه بررسی شود."},
    {name:"فصلنامه مکانیک هوافضا", org:"نشریه علمی فارسی", type:"مقاله پژوهشی", lang:"FA", trust:"داوری‌شده", url:"https://maj.ihu.ac.ir/", note:"مقالات فارسی پژوهشی در دینامیک، کنترل، سازه و موضوعات هوافضا با دسترسی آزاد."},
    {name:"گرایش فناوری ماهواره", org:"دانشگاه صنعتی امیرکبیر", type:"مسیر دانشگاهی", lang:"FA", trust:"دانشگاهی", url:"https://ae.aut.ac.ir/content/2288/", note:"معرفی دانشگاهی گرایش فناوری ماهواره و زمینه آموزشی مرتبط."},
    {name:"Rocket & Launch Vehicles", org:"ERAU Open Textbook", type:"آموزش پیشرانش", lang:"EN", trust:"دانشگاهی", url:"https://eaglepubs.erau.edu/introductiontoaerospaceflightvehicles/chapter/rocket-performance/", note:"معادله موشک، مرحله‌بندی، اتلاف‌ها، Max-Q و طراحی مقدماتی صعود."},
    {name:"Space Mission Analysis and Design", org:"Wertz, Larson et al.", type:"کتاب مرجع", lang:"EN", trust:"دانشگاهی", url:"https://www.smad.com/", note:"مرجع کلاسیک طراحی مأموریت؛ برای مطالعه عمیق معماری، مدار، محموله و بخش زمینی."}
  ]
};
