(()=>{
const A=(id,domain,level,fa,en,summary,prereq,body,equations=[],example='',keywords=[])=>({id,domain,level,title:{fa,en},summary,prereq,body,equations,example,keywords});
window.MADAR_KNOWLEDGE_DOMAINS={
 launchers:{fa:'پرتابگر و پیشرانش',en:'Launch Vehicles & Propulsion',color:'#ff9e64'},
 orbital:{fa:'مکانیک مداری',en:'Orbital Mechanics',color:'#72efc6'},
 design:{fa:'طراحی ماهواره',en:'Satellite Design',color:'#60cceb'},
 control:{fa:'کنترل ماهواره',en:'Spacecraft Control',color:'#b9a1ff'},
 remote:{fa:'سنجش‌ازدور',en:'Remote Sensing',color:'#9be15d'}
};
window.MADAR_KNOWLEDGE_LEVELS={foundation:{fa:'مقدماتی',en:'Foundation'},university:{fa:'دانشگاهی',en:'University'},advanced:{fa:'معلومات پیشرفته',en:'Advanced Knowledge'}};
window.MADAR_KNOWLEDGE=[
// LAUNCH VEHICLES — FOUNDATION
A('lv-taxonomy','launchers','foundation','طبقه‌بندی کامل پرتابگرها','Launch Vehicle Taxonomy','پرتابگرها را می‌توان بر اساس مقصد، ظرفیت، محل پرتاب، نوع پیشرانه، تعداد مراحل و قابلیت بازیابی طبقه‌بندی کرد.','فیزیک دبیرستان',["پرتابگر Suborbital الزاماً سرعت مداری نمی‌سازد؛ پرتابگر Orbital باید انرژی و جهت سرعت کافی ایجاد کند. پرتابگر زمینی، هوابرد و دریایی هرکدام محدودیت عملیاتی و عملکرد متفاوت دارند.","از نظر معماری می‌توان از Sounding rocket، Small-lift، Medium-lift، Heavy-lift و Super-heavy؛ از نظر مصرف از Expendable، Partially reusable و Fully reusable؛ و از نظر پیشران از Solid، Liquid و Hybrid نام برد."],[],"Falcon 9 یک پرتابگر مداری دومرحله‌ای، مایع و با مرحله اول بازیابی‌پذیر است؛ PSLV یک پرتابگر چندمرحله‌ای جامد–مایع مصرفی است.",['orbital','suborbital','small lift','heavy lift','reusable','مصرفی','هوابرد','دریاپرتاب']),
A('lv-lift-class','launchers','foundation','رده ظرفیت و معنی Payload to Orbit','Launch Capacity Classes','ظرفیت اعلام‌شده فقط با ذکر مدار، میل، پایگاه و پروفایل بازیابی معنا دارد.','آشنایی با LEO و GTO',["Small-lift معمولاً محموله‌های کوچک LEO را حمل می‌کند؛ Medium و Heavy برای منظومه‌ها، فضاپیماهای بزرگ یا مدارهای پرانرژی استفاده می‌شوند. مرز عددی رده‌ها میان منابع یکسان نیست.","عبارت ۲۰ تن به LEO به معنی ۲۰ تن به SSO یا GTO نیست. تغییر میل، ارتفاع، بازیابی مرحله و Fairing عملکرد قابل استفاده را تغییر می‌دهد."],[],"ظرفیت Expendable فالکن ۹ از ظرفیت مأموریتی که بوستر باید فرود بیاید بیشتر است.",['payload capacity','LEO capacity','GTO capacity','کلاس سبک','کلاس سنگین']),
A('lv-stages-basic','launchers','foundation','چرا موشک چندمرحله‌ای است؟','Why Rockets Use Stages','مرحله‌بندی جرم مخزن و موتور مصرف‌شده را حذف و نسبت جرمی مؤثر را بهتر می‌کند.','جرم و انرژی',["در Serial staging مرحله‌ها به‌ترتیب می‌سوزند؛ در Parallel staging بوستر و Core هم‌زمان کار می‌کنند. مرحله بالا برای خلأ، Restart و دقت تزریق بهینه می‌شود.","مرحله بیشتر عملکرد را بالا می‌برد اما مکانیزم جدایش، Ignition و نقاط شکست تازه ایجاد می‌کند. انتخاب تعداد مرحله یک Trade میان جرم سازه، Isp، رانش، هزینه و قابلیت اطمینان است."],[],"Soyuz از بوسترهای موازی و مراحل سری استفاده می‌کند؛ Electron می‌تواند Kick Stage جداگانه برای تحویل دقیق داشته باشد.",['staging','serial','parallel','upper stage','booster']),
A('lv-propellants-basic','launchers','foundation','انواع پیشرانه موشکی','Rocket Propellant Families','جامد، مایع و هیبرید از نظر کنترل، چگالی، بهره‌وری و عملیات تفاوت بنیادی دارند.','شیمی و فشار مقدماتی',["موتور جامد ساده و آماده است ولی پس از روشن‌شدن کنترل‌پذیری کمی دارد. موتور مایع Throttle، Shutdown و Restart می‌دهد اما شیر و پمپ پیچیده دارد. Hybrid سوخت جامد و اکسیدکننده سیال را ترکیب می‌کند.","LOX/RP-1 چگال و پررانش؛ LOX/LH2 کم‌چگال ولی دارای Isp بالا؛ و LOX/CH4 گزینه مناسب برای پاکی احتراق و استفاده مجدد است. پیشرانه Hypergolic ذخیره‌پذیر اما سمی است."],[],"مرحله اول معمولاً رانش و چگالی را ترجیح می‌دهد؛ مرحله بالا می‌تواند Isp و Restart را مهم‌تر بداند.",['solid','liquid','hybrid','LOX','RP-1','LH2','methane','hypergolic']),
// LAUNCHERS — UNIVERSITY
A('lv-engine-cycles','launchers','university','چرخه‌های موتور مایع','Liquid Rocket Engine Cycles','چرخه تغذیه تعیین می‌کند انرژی توربوپمپ چگونه تولید و محصولات Preburner کجا مصرف شوند.','ترمودینامیک و سیالات',["Pressure-fed ساده اما مخزن سنگین است. Gas-generator بخشی از پیشرانه را برای توربین مصرف و تخلیه می‌کند. Staged-combustion محصولات Preburner را وارد محفظه اصلی می‌کند و کاراتر اما پرفشارتر است.","Expander cycle از گرمای جذب‌شده در Cooling jacket استفاده می‌کند و برای موتورهای هیدروژنی مرحله بالا مناسب است. Electric-pump پمپ را با باتری می‌چرخاند و برای موتور کوچک، سادگی توربوماشین را با جرم باتری مبادله می‌کند."],["F = ṁVe + (Pe−Pa)Ae","Isp = F/(ṁg₀)"],"Merlin از Gas-generator، Raptor از Full-flow staged combustion و Rutherford از Electric-pump استفاده می‌کنند.",['gas generator','staged combustion','full flow','expander','electric pump','pressure fed']),
A('lv-staging-math','launchers','university','محاسبه مرحله‌بندی و Payload fraction','Staging Mathematics','دلتاوی هر مرحله باید با جرم تمام اجزایی که هنگام Burn حمل می‌شوند محاسبه شود.','لگاریتم و معادله موشک',["برای مرحله پایین، مرحله‌های بالاتر و Payload جزو جرم نهایی‌اند. Structural coefficient و Propellant fraction عملکرد را محدود می‌کنند. جمع دلتاوی مرحله‌ها باید نیاز مسیر و اتلاف‌ها را با Reserve پوشش دهد.","بهینه‌سازی توزیع دلتاوی بین مراحل به Isp، ضریب سازه، رانش و قیود مسیر وابسته است. بیشینه‌کردن دلتاوی بدون توجه به Thrust-to-weight یا Max-Q طراحی قابل پرواز نمی‌سازد."],["Δvᵢ = Ispᵢ g₀ ln(m₀ᵢ/mfᵢ)","λ = mpayload/m₀"],"یک Spreadsheet مرحله‌ای باید جرم Fairing، Adapter، Residual و Reserve را نیز لحاظ کند.",['payload fraction','structural coefficient','mass ratio','delta v allocation']),
A('lv-reuse','launchers','university','طراحی مصرفی در برابر استفاده مجدد','Expendable vs Reusable Design','بازیابی هزینه سخت‌افزار را کاهش می‌دهد اما جرم، دلتاوی، حرارت و عملیات اضافه می‌کند.','معادله موشک و انتقال حرارت',["مرحله بازیابی‌پذیر به Heat protection، Guidance، RCS، Grid fin، Landing propulsion و Landing gear نیاز دارد. این جرم از Payload یا Reserve مأموریت کم می‌شود.","Return-to-launch-site دلتاوی بیشتری از Downrange landing می‌خواهد. ارزش اقتصادی به نرخ پرواز، هزینه Refurbishment، عمر قطعه و Reliability بستگی دارد؛ نه صرفاً موفقیت فرود."],["Payload penalty ≈ function(reserve propellant + recovery hardware)"],"Falcon 9 برای مأموریت پرانرژی گاهی بوستر را مصرف می‌کند؛ زیرا عملکرد مأموریت بر بازیابی اولویت دارد.",['reentry','RTLS','droneship','refurbishment','thermal protection']),
A('lv-selection','launchers','university','انتخاب پرتابگر برای یک ماهواره','Launch Vehicle Selection','انتخاب باید هم عملکرد و هم Interface، برنامه، ریسک و هزینه چرخه مأموریت را بسنجد.','طراحی مأموریت مقدماتی',["پارامترها شامل جرم تر، مدار تزریق، میل، حجم Fairing، مرکز جرم، بار و فرکانس، محیط شوک/آکوستیک، دقت تزریق، پنجره و Rideshare هستند.","یک پرتابگر با ظرفیت اسمی کافی ممکن است به‌دلیل Envelope، دسترس‌نبودن پایگاه یا Drift ناشی از Rideshare نامناسب باشد. Trade study باید گزینه‌ها و حساسیت به رشد جرم را ثبت کند."],[],"برای CubeSat، Dedicated launch کنترل مدار می‌دهد ولی Rideshare ارزان‌تر است؛ هزینه اصلاح مدار باید در تصمیم وارد شود.",['launcher selection','rideshare','fairing envelope','injection accuracy','user guide']),
// LAUNCHERS — ADVANCED
A('lv-trajectory-opt','launchers','advanced','بهینه‌سازی مسیر صعود و تخصیص جرم','Ascent Trajectory Optimization','یک مسئله کنترل بهینه چندفازی برای بیشینه‌کردن Payload تحت قیود دینامیک، بار، حرارت و ناحیه سقوط است.','معادلات دیفرانسیل، کنترل بهینه، سیالات',["State شامل موقعیت، سرعت، جرم و نگرش است و Control می‌تواند Throttle، زاویه رانش و زمان جدایش باشد. قیود Max-Q، زاویه حمله، Heating، Thrust، G-load و Terminal state اعمال می‌شوند.","روش‌های Direct transcription، Collocation و Multiple shooting مسئله پیوسته را به NLP تبدیل می‌کنند. راه‌حل باید سپس با مدل 6-DOF و پراکندگی Monte Carlo راستی‌آزمایی شود."],["ṁ = −T/(Isp g₀)","ẋ = f(x,u,t)"],"کمینه‌کردن زمان صعود همیشه بهترین نیست؛ مسیر سریع می‌تواند بار و Heating را نقض کند.",['optimal control','collocation','multiple shooting','6DOF','Monte Carlo','NLP']),
A('lv-turbopump','launchers','advanced','توربوپمپ، Cavitation و پایداری احتراق','Turbomachinery and Combustion Stability','موتور پررانش به انتقال توان بسیار زیاد، ورودی پایدار و احتراق بدون Coupling نیاز دارد.','سیالات تراکم‌پذیر، توربوماشین، احتراق',["NPSP ناکافی Cavitation و آسیب Inducer ایجاد می‌کند. Rotordynamics، Seal، Bearing و تغییرات دمای Cryogenic طراحی را سخت می‌کنند.","ناپایداری احتراق می‌تواند Low-frequency Chug یا High-frequency Acoustic mode باشد. Injector pattern، Chamber acoustics و Feed-system coupling باید با آزمون و مدل بررسی شوند."],["NPSH/NPSP margin > required","f_acoustic ~ nc/(2L)"],"افزایش فشار محفظه عملکرد را بهتر می‌کند، اما بار توربوپمپ، Cooling و خطر Instability را افزایش می‌دهد.",['turbopump','cavitation','inducer','chug','combustion instability','rotordynamics']),
A('lv-aeroelastic','launchers','advanced','Aeroelasticity و بارهای کوپل‌شده','Aeroelastic and Coupled Loads','سازه بلند و سبک با جریان، Slosh، Thrust vector و کنترل برهم‌کنش دارد.','دینامیک سازه، کنترل، CFD مقدماتی',["Modal frequency، Bending، Torsion و Buffet باید در طول تغییر جرم و فشار بررسی شوند. Control–structure interaction می‌تواند فرمان TVC را با مود انعطاف‌پذیر تقویت کند.","Coupled loads analysis مدل پرتابگر و Payload را ترکیب می‌کند. Notching در آزمون از Over-test ماهواره جلوگیری می‌کند، ولی باید بر مدل معتبر تکیه داشته باشد."],["M q̈ + C q̇ + K q = F(t)"],"Max-Q ممکن است بیشینه q باشد ولی بیشینه Bending moment در زمان دیگری و با Wind profile خاص رخ دهد.",['aeroelasticity','flutter','buffet','coupled loads','slosh','notching']),
A('lv-reliability','launchers','advanced','قابلیت اطمینان، FTS و Abort','Launch Reliability and Flight Safety','ایمنی پرتاب میان موفقیت مأموریت، حفاظت عمومی، تحمل خرابی و تصمیم Abort تعادل ایجاد می‌کند.','احتمال، FTA/FMEA، دینامیک پرواز',["Fault tree مسیرهای Loss of thrust، Loss of control، Structural breakup و Range violation را می‌سنجد. Engine-out فقط اگر Guidance و Propellant margin اجازه دهد Fault tolerance واقعی است.","Autonomous flight safety موقعیت و Corridor را پایش و در صورت نقض فرمان Termination می‌دهد. مأموریت سرنشین‌دار علاوه بر آن Launch escape و Abort modeهای وابسته به زمان دارد."],[],"افزونگی دو رایانه با نرم‌افزار یکسان، خطای Systematic مشترک را حذف نمی‌کند.",['FTA','FMEA','AFTS','engine out','abort','launch escape','common cause']),
// ORBITAL — FOUNDATION
A('om-frames','orbital','foundation','چارچوب‌های مرجع، زمان و بردار حالت','Reference Frames, Time and State Vectors','هیچ موقعیت یا سرعتی بدون Frame، Epoch و Time scale کامل نیست.','بردار و مختصات',["ECI تقریباً لخت، ECEF همراه دوران زمین و LVLH همراه مدار است. تبدیل میان آن‌ها برای Ground track، Pointing و Navigation ضروری است.","UTC، TAI، TT و UT1 یکسان نیستند. Leap second و Earth orientation در دقت بالا مهم‌اند. بردار حالت شش مؤلفه موقعیت و سرعت دارد."],["x = [rᵀ vᵀ]ᵀ"],"یک TLE بدون Epoch برای پیش‌بینی معنا ندارد؛ عناصر با زمان کهنه می‌شوند.",['ECI','ECEF','LVLH','UTC','TAI','epoch','state vector']),
A('om-elements','orbital','foundation','از بردار حالت تا عناصر مداری','State Vectors and Orbital Elements','عناصر کلاسیک شکل و جهت مدار را فشرده بیان می‌کنند، اما در دایره و استوا تکینگی دارند.','مکانیک مداری پایه',["a و e اندازه/شکل، i و Ω صفحه، ω جهت حضیض و ν موقعیت جسم را مشخص می‌کنند. تبدیل State↔Elements از بردار مومنتوم زاویه‌ای و Eccentricity استفاده می‌کند.","برای مدار دایروی یا استوایی از عناصر Equinoctial یا ترکیب‌هایی مانند Argument of latitude استفاده می‌شود."],["h = r × v","e⃗ = (v×h)/μ − r̂"],"میل ISS حدود ۵۱٫۶ درجه پوشش عرضی را نشان می‌دهد، نه ارتفاع را.",['orbital elements','equinoctial','RAAN','true anomaly','eccentricity vector']),
A('om-maneuver-basics','orbital','foundation','منطق مانور مداری','Orbital Maneuver Intuition','جهت و نقطه Burn تعیین می‌کند کدام عنصر مدار تغییر کند.','دایره و بیضی',["Burn مماسی Prograde انرژی و نقطه مقابل مدار را بالا می‌برد؛ Retrograde پایین می‌آورد. Burn شعاعی و Out-of-plane اثر متفاوت دارند.","مانور Impulsive تقریب Burn کوتاه است. موتور کم‌رانش در بخش بزرگی از مدار می‌سوزد و این تقریب را نقض می‌کند."],["Δε = v·Δv + |Δv|²/2"],"برای بالا‌بردن Apogee در Perigee، Burn پیشرو انجام می‌شود.",['prograde','retrograde','radial burn','normal burn','impulsive']),
A('om-groundtrack','orbital','foundation','رد زمینی، پوشش و Revisit','Ground Track, Coverage and Revisit','دوران زمین زیر صفحه مدار، مسیر مشاهده و زمان بازگشت را می‌سازد.','هندسه و دوره مدار',["Ground track به دوره، میل، RAAN و دوران زمین وابسته است. Coverage ناحیه قابل مشاهده و Revisit فاصله زمانی مشاهده دوباره است؛ این دو یکسان نیستند.","ارتفاع Footprint را زیاد می‌کند، اما برای اپتیک ثابت تفکیک را کاهش می‌دهد. منظومه Revisit را با تعداد صفحه و Phasing بهتر می‌کند."],[],"دو ماهواره Sentinel-2 با اختلاف فاز ۱۸۰ درجه زمان بازدید را نسبت به یک ماهواره کاهش می‌دهند.",['ground track','coverage','revisit','swath','repeat cycle']),
// ORBITAL — UNIVERSITY
A('om-lambert','orbital','university','مسئله Lambert','Lambert Problem','با دو موقعیت و زمان پرواز، مدار انتقال و سرعت‌های ابتدا/انتها تعیین می‌شوند.','بردار، Kepler، روش عددی',["Lambert پایه طراحی انتقال، Rendezvous و Pork-chop plot است. امکان Short/long way، چند دور و شاخه‌های مختلف وجود دارد.","حل‌گر Universal variable یا Izzo باید نزدیک حالت‌های Parabolic و هندسه ۱۸۰ درجه پایدار باشد. اختلاف سرعت با مدارهای اولیه و نهایی دلتاوی مأموریت را می‌دهد."],["Given r₁,r₂,Δt → v₁,v₂"],"برای انتقال زمین–مریخ، موقعیت دو سیاره و زمان پرواز به Lambert داده و C3 محاسبه می‌شود.",['Lambert','universal variables','Izzo','pork chop','C3']),
A('om-rendezvous','orbital','university','ملاقات مداری و حرکت نسبی','Orbital Rendezvous and Relative Motion','رسیدن به همان نقطه کافی نیست؛ موقعیت و سرعت نسبی باید هم‌زمان بسته شوند.','مانور مداری و جبر خطی',["Phasing مدار زمان رسیدن را تنظیم می‌کند. در نزدیکی Target، Hill/LVLH و معادلات Clohessy–Wiltshire حرکت نسبی مدار دایروی را خطی می‌کنند.","عملیات شامل Far-range، Proximity، Hold point، Approach corridor و Collision avoidance است. Navigation نسبی از GNSS، Radar، Lidar یا Vision می‌آید."],["ẍ−3n²x−2nẏ=0","ÿ+2nẋ=0","z̈+n²z=0"],"جسم پایین‌تر از Target سریع‌تر حرکت می‌کند و می‌تواند برای Catch-up از مدار Phasing پایین استفاده کند.",['rendezvous','Clohessy Wiltshire','Hill equations','proximity operations','phasing']),
A('om-od-basic','orbital','university','تعیین مدار و Least Squares','Orbit Determination','اندازه‌گیری Range، Doppler، Angle یا GNSS برای برآورد State و عدم‌قطعیت ترکیب می‌شوند.','آمار، مشتق، ماتریس',["Batch least squares Residual اندازه‌گیری‌ها را با وزن کمینه می‌کند. State transition matrix حساسیت اندازه‌گیری به State اولیه را منتقل می‌کند.","Observability به نوع و هندسه داده وابسته است. Bias ایستگاه، Clock و Drag coefficient ممکن است همراه مدار تخمین زده شوند."],["δx̂=(HᵀWH)⁻¹HᵀWδy","P=(HᵀWH)⁻¹"],"فقط Angle کوتاه از یک ایستگاه Range را ضعیف تعیین می‌کند؛ Arc بلند یا داده مکمل لازم است.",['orbit determination','least squares','residual','observability','covariance']),
A('om-special-orbits','orbital','university','Repeat Ground Track و Frozen Orbit','Repeat and Frozen Orbits','برخی مدارها با استفاده از Resonance و اغتشاش برای مأموریت خاص طراحی می‌شوند.','J2 و Ground track',["Repeat ground track نسبت دوره ماهواره به روز زمین را طوری انتخاب می‌کند که رد پس از تعداد دور تکرار شود. SSO می‌تواند با Repeat cycle ترکیب شود.","Frozen orbit ترکیب e و ω را طوری انتخاب می‌کند که تغییرات بلندمدت کم شود. برای Altimetry و Mapping، ثبات ارتفاع و Ground track ارزشمند است."],["N·T ≈ M·T_Earth"],"چرخه تکرار Landsat امکان مقایسه منظم یک مسیر زمینی را فراهم می‌کند.",['repeat ground track','frozen orbit','resonance','J2','mean elements']),
// ORBITAL — ADVANCED
A('om-propagation','orbital','advanced','انتشار عددی مدار و مدل نیرو','Numerical Orbit Propagation','دقت بالا نیازمند انتگرال‌گیری State همراه مدل گرانش، جو، اجرام ثالث و تابش است.','ODE عددی، آنالیز خطا، مکانیک سماوی',["مدل می‌تواند شامل Harmonics میدان زمین، Drag با جو متغیر، Solar radiation pressure، Third body، Relativity و Maneuver باشد. Integrator تطبیقی مانند Dormand–Prince خطای موضعی را کنترل می‌کند.","دقت بیش از کیفیت داده و مدل فیزیکی نمی‌شود. Frame، Earth orientation، Shadow و Area/mass باید سازگار باشند."],["r̈ = −μr/r³ + aJ2 + aDrag + aSRP + a3body"],"کاهش Tolerance انتگرال‌گیر وقتی چگالی جو نامعلوم است الزاماً پیش‌بینی LEO را بهتر نمی‌کند.",['numerical propagation','force model','Dormand Prince','harmonics','SRP','third body']),
A('om-ekf','orbital','advanced','EKF/UKF و تخمین پیوسته مدار','Sequential Orbit Estimation','فیلتر State و Covariance را با مدل دینامیک و اندازه‌گیری‌های زمان‌دار به‌روز می‌کند.','احتمال، کنترل خطی، OD',["EKF مدل را حول تخمین خطی می‌کند؛ UKF نقاط Sigma را از دینامیک غیرخطی عبور می‌دهد. Process noise خطای مدل مانند Drag یا Maneuver کوچک را نمایندگی می‌کند.","Consistency با Innovation و NEES/NIS بررسی می‌شود. Outlier rejection، Maneuver detection و Smoothing برای سامانه عملیاتی مهم‌اند."],["x̂⁺=x̂⁻+K(y−h(x̂⁻))","K=P⁻Hᵀ(HP⁻Hᵀ+R)⁻¹"],"R کوچک غیرواقعی فیلتر را بیش‌اعتماد و در برابر Bias حسگر ناپایدار می‌کند.",['EKF','UKF','process noise','innovation','smoothing','NIS']),
A('om-lowthrust','orbital','advanced','مسیرهای Low-thrust و کنترل بهینه','Low-Thrust Trajectory Design','رانش کم پیوسته، مدار را آهسته تغییر می‌دهد و به بهینه‌سازی جهت رانش و زمان نیاز دارد.','کنترل بهینه، Calculus of variations',["روش Edelbaum تقریب انتقال دایروی و تغییر میل را می‌دهد. Direct collocation و Indirect shooting برای قیود پیچیده استفاده می‌شوند.","Eclipse، Power throttling، Duty cycle، Radiation و Collision در مسیر ماه‌ها باید مدل شوند. کمینه سوخت و کمینه زمان جواب یکسان ندارند."],["ẋ=f(x,u,t)","ṁ=−T/(Isp g₀)"],"Electric orbit raising جرم پیشرانه GEO را کم می‌کند ولی زمان و عبور تابشی را افزایش می‌دهد.",['low thrust','Edelbaum','collocation','electric propulsion','optimal control']),
A('om-cr3bp','orbital','advanced','مسئله سه‌جسم، لاگرانژ و NRHO','CR3BP, Lagrange Points and NRHO','در چارچوب چرخان دو جرم اصلی، نقاط تعادل و خانواده مدارهای Halo، Lissajous و NRHO ظاهر می‌شوند.','دینامیک غیرخطی، دستگاه چرخان، مقادیر ویژه',["CR3BP با پارامتر جرم μ و ثابت Jacobi توصیف می‌شود. نقاط L1/L2/L3 Collinear ناپایدار و L4/L5 در شرایطی پایدارند.","Differential correction و Multiple shooting مدار Periodic را می‌سازند. Manifoldهای پایدار/ناپایدار انتقال کم‌انرژی فراهم می‌کنند. NRHO خانواده‌ای Halo نزدیک ماه با کاربرد Gateway است."],["C_J=2Ω−v²","∇Ω=0 at Lagrange points"],"JWST روی نقطه L2 ساکن نیست؛ در مدار Halo/Lissajous پیرامون آن حرکت و Station keeping می‌کند.",['CR3BP','Lagrange','halo orbit','Lissajous','NRHO','manifold','Jacobi']),
// SATELLITE DESIGN — FOUNDATION
A('sd-process','design','foundation','فرایند طراحی ماهواره از ایده تا عملیات','Satellite Design Process','طراحی با هدف و نیازمندی آغاز و از Concept، PDR، CDR، ساخت، آزمون و عملیات عبور می‌کند.','بدون پیش‌نیاز',["هدف کاربر به MOE، نیاز سامانه و نیاز زیرسامانه Flow down می‌شود. ConOps رفتار مأموریت در حالت عادی و خطا را توصیف می‌کند.","بودجه جرم، توان، داده، دلتاوی، حرارت و لینک باید هم‌زمان بسته شوند. تغییر Payload روی تقریباً همه Bus اثر می‌گذارد."],[],"برای پایش آتش، زمان تحویل محصول و Revisit به اندازه تفکیک دوربین مهم‌اند.",['mission design','requirements','ConOps','PDR','CDR','budgets']),
A('sd-bus-payload','design','foundation','Payload، Bus و Interface','Payload, Bus and Interfaces','Payload هدف اصلی را انجام و Bus توان، حرارت، داده، وضعیت و ارتباط لازم را فراهم می‌کند.','معماری سیستم',["Interface فقط Connector نیست؛ شامل بار، Envelope، توان، Protocol، Timing، Heat و عملیات است. ICD توافق دو طرف را ثبت می‌کند.","Payload-driven design نیاز Pointing، Data volume، Duty cycle و Thermal dissipation را به زیرسامانه‌ها تخصیص می‌دهد."],[],"دوربین با Exposure طولانی، Jitter سازه و ADCS را محدود می‌کند.",['payload','spacecraft bus','ICD','interface','allocation']),
A('sd-budgets','design','foundation','بودجه‌ها، Margin و Reserve','Engineering Budgets and Margins','بودجه‌ها زبان مشترک زیرسامانه‌ها هستند و رشد طراحی را قابل کنترل می‌کنند.','درصد و جمع',["Mass budget شامل CBE، Growth allowance و System margin است. Power budget باید Mode، Eclipse و Peak را ببیند. Data budget تولید، ذخیره و Downlink را متعادل می‌کند.","Margin فاصله عملکرد پیش‌بینی از Requirement است؛ Reserve منبع تحت کنترل مدیریت. جمع حاشیه‌های محلی جای تحلیل سطح سیستم را نمی‌گیرد."],["Margin = Capability − Requirement"],"اگر تولید روزانه داده از Downlink بیشتر باشد، حافظه هرقدر بزرگ باشد سرانجام پر می‌شود.",['mass budget','power budget','data budget','margin','reserve']),
A('sd-lifecycle','design','foundation','چرخه عمر، آزمون و بازبینی','Lifecycle, Reviews and Test','هر فاز شواهد بلوغ مشخصی تولید می‌کند و آزمون باید با خطر و محیط واقعی مرتبط باشد.','مبانی مهندسی سیستم',["SRR نیازها، PDR معماری، CDR طراحی نهایی، TRR آمادگی آزمون، FRR آمادگی پرواز و ORR آمادگی عملیات را می‌سنجد.","Qualification طراحی را برای محیط اثبات و Acceptance عیب ساخت واحد پروازی را غربال می‌کند. Protoflight ترکیبی با ریسک و سطح آزمون خاص است."],[],"آزمون ارتعاش بدون Notching معتبر می‌تواند Payload را بیش از محیط پرواز تحریک کند.",['SRR','PDR','CDR','qualification','acceptance','protoflight']),
// SATELLITE DESIGN — UNIVERSITY
A('sd-eps','design','university','سایزبندی آرایه خورشیدی و باتری','Power System Sizing','توان باید برای بدترین هندسه خورشید و پایان عمر، انرژی بار و Eclipse را با Margin تأمین کند.','مدار، انرژی، مدار الکتریکی',["آرایه با Flux، Efficiency، Packing، Temperature، Incidence و Degradation سایز می‌شود. باتری از Eclipse energy، DoD مجاز، بازده و عمر چرخه به دست می‌آید.","Peak load، Inrush، Heater و Safe mode جدا بررسی می‌شوند. MPPT و DET دو معماری تنظیم متداول‌اند."],["P_EOL=P_BOL·L_deg·L_temp·cosθ","C_batt ≥ E_eclipse/(V·DoD·η)"],"بار ۴۰ W در Eclipse ۳۵ دقیقه حداقل ۲۳٫۳ Wh ایده‌آل می‌خواهد؛ ظرفیت واقعی بزرگ‌تر است.",['solar array sizing','battery sizing','EOL','DoD','MPPT','eclipse']),
A('sd-thermal','design','university','طراحی حرارتی Hot/Cold Case','Spacecraft Thermal Design','در خلأ، هدایت داخلی و تابش خارجی دما را تعیین می‌کنند؛ حالت Hot و Cold باید جدا بسته شوند.','انتقال حرارت',["مدل Lumped-node شبکه Conductance و Radiation می‌سازد. ورودی‌ها Sun، Albedo، Earth IR، Payload و Electronics هستند. خروجی از Radiator به فضاست.","Coating با α/ε، MLI، Heat pipe، Strap و Heater ابزار کنترل‌اند. Contact conductance و View factor عدم‌قطعیت مهم دارند."],["Q_rad=εσA(T⁴−Tspace⁴)","C dT/dt=ΣQ"],"رادیاتور رو به خورشید ممکن است به‌جای دفع حرارت، انرژی جذب کند.",['thermal balance','hot case','cold case','MLI','radiator','heater','view factor']),
A('sd-structure','design','university','سازه، بار پرتاب و تحلیل مودال','Structure and Modal Design','سازه باید سبک، سخت، پایدار و سازگار با Load envelope پرتابگر باشد.','مقاومت مصالح و ارتعاشات',["Quasi-static، Sine، Random، Acoustic و Shock ورودی‌اند. FEM فرکانس و Stress را پیش‌بینی و Modal survey مدل را Correlate می‌کند.","مرکز جرم، Moment of inertia، Bolt preload، Insert و Interface ring حیاتی‌اند. Stability اپتیک می‌تواند CTE پایین بخواهد."],["M q̈+C q̇+K q=F(t)","f_n≈(1/2π)√(k/m)"],"افزایش ضخامت Stress را کم می‌کند اما جرم و فرکانس/بار Interface را تغییر می‌دهد.",['FEM','modal analysis','random vibration','shock','acoustic','CTE']),
A('sd-subsystem-sizing','design','university','سایزبندی ADCS، مخابرات و پیشرانش','ADCS, Communications and Propulsion Sizing','سه زیرسامانه باید از نیاز Pointing، داده و مانور به ظرفیت سخت‌افزار برسند.','کنترل، مخابرات، معادله موشک',["ADCS از Torque disturbance و Slew profile به Wheel torque/momentum و Magnetorquer می‌رسد. Link budget آنتن، توان، Range، G/T و Eb/N0 را می‌بندد.","Propellant از مجموع Δv و Isp محاسبه می‌شود؛ Residual، Mixture ratio، Blowdown و Duty cycle به جرم واقعی اضافه می‌شوند."],["H_wheel ≥ ∫τ_dist dt","m_p=m₀(1−e^(−Δv/ve))"],"انتخاب Reaction wheel فقط بر اساس Torque بدون بررسی Momentum storage ناقص است.",['ADCS sizing','reaction wheel','link budget','propellant budget','thruster sizing']),
// SATELLITE DESIGN — ADVANCED
A('sd-mbse','design','advanced','MBSE، SysML و بستن معماری','Model-Based Systems Engineering','مدل واحد روابط نیاز، عملکرد، جزء، Interface، Verification و ریسک را قابل ردیابی می‌کند.','مهندسی سیستم و مدل‌سازی',["Requirement، Block، Activity، State و Parametric diagram دیدهای مکمل‌اند. مدل باید سؤال مهندسی را پاسخ دهد، نه اینکه فقط نمودار بیشتری تولید کند.","Digital thread تغییر نیاز را تا بودجه، Interface، Test و Operation دنبال می‌کند. Configuration و Validation مدل بخش اصلی فرایند است."],[],"تغییر نرخ داده Payload باید اثر روی حافظه، Downlink، توان و برنامه Ground را در مدل نشان دهد.",['MBSE','SysML','digital thread','parametric model','traceability']),
A('sd-reliability','design','advanced','Reliability، FMEA/FTA و Fault Tolerance','Reliability and Fault-Tolerant Design','قابلیت اطمینان با Redundancy صرف ساخته نمی‌شود؛ معماری، پوشش تشخیص و Common cause باید تحلیل شود.','احتمال و مهندسی سیستم',["FMEA از Failure mode به اثر و کنترل می‌رود؛ FTA از Top event به Cut set. Reliability block diagram احتمال موفقیت مسیرها را مدل می‌کند.","Cold/warm/hot redundancy، Cross-strapping، voting و graceful degradation هزینه جرم، توان و نرم‌افزار دارند. FDIR باید False alarm و Detection latency را بسنجد."],["R_series=∏Rᵢ","R_parallel=1−∏(1−Rᵢ)"],"دو رایانه یکسان با نرم‌افزار یکسان در برابر خطای مشترک نرم‌افزار مستقل نیستند.",['reliability','FMEA','FTA','RBD','redundancy','FDIR','common cause']),
A('sd-radiation','design','advanced','طراحی تاب‌آور پرتویی','Radiation-Hardened Spacecraft Design','TID، Displacement damage و SEE به انتخاب قطعه، Shielding و معماری نرم‌افزار مرتبط‌اند.','فیزیک نیمه‌رسانا و قابلیت اطمینان',["TID پارامتر قطعه را تجمعی تغییر می‌دهد؛ SEU بیت را برمی‌گرداند؛ SEL مسیر جریان مخرب می‌سازد. Orbit و Solar cycle محیط را تعیین می‌کنند.","راهکارها شامل Rad-hard part، Derating، ECC/Scrubbing، watchdog، current limiting، latch-up protection و Triple modular redundancy است."],[],"Shielding بیشتر همیشه بهتر نیست؛ ذرات ثانویه و جرم باید با Transport analysis بررسی شوند.",['TID','SEE','SEU','SEL','radiation shielding','ECC','scrubbing','TMR']),
A('sd-end2end','design','advanced','کارگاه طراحی از Mission Concept تا CDR','End-to-End Satellite Design to CDR','خروجی طراحی کامل باید نیاز، مدل، بودجه، Interface، ریسک، Test و عملیات را به یک Baseline سازگار تبدیل کند.','تمام مباحث طراحی دانشگاهی',["گام‌ها: Stakeholder/MOE، ConOps، مدار و Payload، Functional architecture، Trade، Allocation، Budgets، Preliminary sizing، PDR، Detailed design، ICD و CDR.","محصول‌ها شامل SRD، SEMP، ConOps، Mass/Power/Data/Δv budgets، CAD/FEM/Thermal/Link models، FMEA، Verification matrix، I&T flow، Ground architecture و Cost/Schedule هستند."],[],"طراحی وقتی بسته است که همه نیازها Verification method، همه Interfaceها مالک، و همه بودجه‌ها Margin قابل دفاع داشته باشند.",['CDR','SRD','SEMP','verification matrix','I&T','BOM','design closure']),
// CONTROL — FOUNDATION
A('ct-dynamics-intro','control','foundation','دینامیک وضعیت ماهواره','Spacecraft Attitude Dynamics','کنترل وضعیت چرخش جسم صلب تحت گشتاور عملگر و محیط است.','بردار و گشتاور',["نگرش جهت Body نسبت به Frame مرجع است و نرخ زاویه‌ای تغییر آن را بیان می‌کند. Moment of inertia پاسخ به Torque را تعیین می‌کند.","گشتاورهای محیطی شامل Gravity-gradient، Drag، Magnetic residual و Solar pressure هستند. کنترل باید Pointing و Stability را با محدودیت عملگر حفظ کند."],["H=Iω","τ=dH/dt"],"ماهواره کشیده حول محور با اینرسی کوچک‌تر به Torque یکسان شتاب زاویه‌ای بیشتری می‌گیرد.",['attitude','rigid body','inertia','disturbance torque','pointing']),
A('ct-representations','control','foundation','نمایش نگرش: Euler، DCM و Quaternion','Attitude Representations','هر نمایش مزیت و محدودیت دارد؛ Frame و ترتیب Rotation باید صریح باشد.','ماتریس و مثلثات',["Euler angles شهودی ولی دارای Gimbal lock هستند. DCM تبدیل مستقیم بردار می‌دهد ولی ۹ مؤلفه با قید Orthogonality دارد.","Quaternion چهار مؤلفه و بدون تکینگی محلی است؛ q و −q یک نگرش را نشان می‌دهند و Normalization لازم است."],["qᵀq=1","CᵀC=I"],"ترتیب 3-2-1 با 1-2-3 یک Rotation یکسان تولید نمی‌کند.",['Euler angles','DCM','quaternion','gimbal lock','frames']),
A('ct-sensors','control','foundation','حسگرهای ADCS','ADCS Sensors','حسگرها نرخ، جهت خورشید/زمین، میدان مغناطیسی و ستاره‌ها را با دقت و نرخ متفاوت می‌سنجند.','اندازه‌گیری مقدماتی',["Gyro سریع ولی دارای Bias drift؛ Star tracker دقیق ولی کند و دارای Sun exclusion؛ Sun sensor و Magnetometer برای Safe mode مفیدند.","هیچ حسگر منفرد کامل نیست. Alignment، Calibration، Noise و Field of view باید در معماری Sensor fusion دیده شوند."],[],"Gyro بین دو اندازه‌گیری Star tracker نگرش را Propagate می‌کند و Star tracker Drift را اصلاح می‌کند.",['gyro','star tracker','sun sensor','magnetometer','Earth sensor']),
A('ct-actuators','control','foundation','عملگرهای کنترل وضعیت','ADCS Actuators','Reaction wheel، Magnetorquer و Thruster محدوده Torque، دقت و منبع مصرف متفاوت دارند.','مومنتوم زاویه‌ای',["Reaction wheel دقیق اما اشباع می‌شود. Magnetorquer بدون سوخت است ولی Torque آن عمود بر میدان زمین و در هر لحظه کم‌بعد است.","Thruster Torque زیاد و Momentum dumping می‌دهد اما پیشرانه و Impulse bit محدود دارد. Control moment gyro برای فضاپیمای بزرگ Torque بالا می‌دهد."],[],"Wheel برای Fine pointing و Magnetorquer برای Desaturation ترکیب رایج LEO است.",['reaction wheel','magnetorquer','thruster','CMG','saturation']),
// CONTROL — UNIVERSITY
A('ct-euler-equations','control','university','معادلات اویلر و سینماتیک Quaternion','Euler Rigid-Body Equations','دینامیک غیرخطی سه‌محوره با ترم Gyroscopic و سینماتیک نگرش ترکیب می‌شود.','دینامیک و معادلات دیفرانسیل',["در محورهای اصلی Iω̇ + ω×Iω = τ. حتی بدون Torque، چرخش حول محور میانی می‌تواند ناپایدار باشد.","Quaternion kinematics نرخ Body را به q̇ نگاشت می‌کند. Convention اسکالر اول/آخر و جهت Frame باید ثابت باشد."],["Iω̇+ω×(Iω)=τ","q̇=½Ω(ω)q"],"کنترلر باید Unwinding ناشی از دوگانگی q و −q را مدیریت کند.",['Euler equations','quaternion kinematics','gyroscopic coupling','intermediate axis']),
A('ct-pd-sizing','control','university','Linearization و طراحی PD/PID','Linearized Attitude Control','نزدیک خطای کوچک، دینامیک هر محور تقریباً مرتبه دوم است و Gain از فرکانس طبیعی و میرایی انتخاب می‌شود.','کنترل خطی و لاپلاس',["برای محور Decoupled، Iθ̈ = τ و قانون PD پاسخ مرتبه دوم می‌سازد. Saturation، Sample rate، Delay و Noise عملکرد واقعی را محدود می‌کنند.","Integral bias را حذف می‌کند اما Windup می‌سازد. Anti-windup و Command shaping برای Slew بزرگ لازم است."],["τ=−Kpθ−Kdθ̇","Kp=Iωn², Kd=2ζIωn"],"دو برابرکردن پهنای باند، Torque و حساسیت به Noise/انعطاف را افزایش می‌دهد.",['PD','PID','linearization','bandwidth','anti windup','damping']),
A('ct-wheel-sizing','control','university','سایزبندی چرخ و Momentum Management','Reaction Wheel Sizing','Torque برای Slew و Momentum capacity برای جذب گشتاور تجمعی دو نیاز جدا هستند.','دینامیک دورانی و انتگرال',["Wheel torque از شتاب زاویه‌ای و Disturbance peak؛ Momentum storage از انتگرال Torque محیطی بین دو Dump به دست می‌آید.","Pyramid چهارچرخ Redundancy و Control allocation می‌دهد. سرعت صفر، Friction، Imbalance و Jitter در Payload دقیق مهم‌اند."],["τ_req=Iα+τdist","H_store≥∫τdist dt"],"چرخی با Torque کافی ممکن است پیش از زمان Dump اشباع شود اگر Momentum capacity کم باشد.",['reaction wheel sizing','momentum storage','wheel pyramid','jitter','desaturation']),
A('ct-kalman','control','university','Sensor Fusion و فیلتر کالمن نگرش','Attitude Kalman Filtering','مدل Gyro و اندازه‌گیری برداری برای تخمین Quaternion و Bias ترکیب می‌شوند.','احتمال، ماتریس، Quaternion',["MEKF خطای کوچک سه‌بعدی را فیلتر و Quaternion مرجع را جدا نگه می‌دارد. Predict با Gyro و Update با Star/Sun/Magnetic vector انجام می‌شود.","Q و R از Noise واقعی می‌آیند. Innovation برای Outlier و سلامت حسگر پایش می‌شود؛ Normalize کردن q جای تحلیل Consistency را نمی‌گیرد."],["K=PHᵀ(HPHᵀ+R)⁻¹"],"وقتی Star tracker کور است، Covariance باید با Drift gyro رشد کند؛ ثابت ماندن آن نشانه مدل غلط است.",['MEKF','Kalman filter','gyro bias','sensor fusion','innovation']),
// CONTROL — ADVANCED
A('ct-optimal','control','advanced','LQR و کنترل بهینه وضعیت','LQR Attitude Control','LQR هزینه خطای State و Control effort را برای مدل خطی کمینه می‌کند.','State space، Riccati، جبر خطی',["انتخاب Q/R ترجمه اولویت Pointing در برابر Torque است. Gain از معادله Riccati می‌آید؛ Units و Scaling روی نتیجه اثر جدی دارند.","Gain scheduling یا Linear parameter varying برای تغییر Inertia/operating point استفاده می‌شود. Constraints مستقیم در LQR استاندارد نیستند."],["J=∫(xᵀQx+uᵀRu)dt","AᵀP+PA−PBR⁻¹BᵀP+Q=0"],"Q بزرگ روی خطای نگرش پاسخ سریع‌تر ولی مصرف Torque و احتمال Saturation را زیاد می‌کند.",['LQR','Riccati','optimal control','gain scheduling','state space']),
A('ct-mpc-robust','control','advanced','MPC، کنترل Robust و H∞','MPC and Robust Control','کنترل پیش‌بین قیود را صریح و کنترل Robust عدم‌قطعیت مدل و اغتشاش را هدف می‌گیرد.','بهینه‌سازی، کنترل مدرن',["MPC در هر گام مسئله افق محدود با محدودیت Wheel speed، Torque و Keep-out حل می‌کند. Real-time feasibility و مدل مناسب ضروری‌اند.","H∞ بیشینه Gain اغتشاش به خروجی را محدود می‌کند. μ-synthesis و Loop-shaping برای عدم‌قطعیت ساختاری‌اند؛ محافظه‌کاری باید ارزیابی شود."],["min Σ||x−xref||Q²+||u||R² subject to dynamics,constraints","||Tzw||∞<γ"],"MPC می‌تواند Slew را بدون اشباع Wheel برنامه‌ریزی کند، ولی حل‌گر دیرهنگام خود یک Failure mode است.",['MPC','H infinity','robust control','constraints','real time optimization']),
A('ct-nonlinear-flexible','control','advanced','کنترل غیرخطی و فضاپیمای انعطاف‌پذیر','Nonlinear and Flexible Spacecraft Control','Slew بزرگ، Quaternion و آرایه انعطاف‌پذیر فرض خطی/صلب را نقض می‌کنند.','Lyapunov، مودال، کنترل غیرخطی',["کنترل Quaternion مبتنی بر Lyapunov پایداری Almost-global می‌دهد. Sliding mode در برابر عدم‌قطعیت مقاوم ولی Chattering دارد.","Flexible modes با Wheel/CMG کوپل می‌شوند. Input shaping، Notch و Bandwidth separation تحریک را کم می‌کنند؛ مدل مودال باید Correlate شود."],["V=1−q₀+½ωᵀIω","M q̈+C q̇+K q=B u"],"فرمان Slew سریع می‌تواند آرایه خورشیدی را به نوسان درآورد و پس از پایان فرمان Jitter باقی بگذارد.",['nonlinear control','Lyapunov','sliding mode','flexible spacecraft','input shaping','notch']),
A('ct-hil','control','advanced','SIL/HIL و اعتبارسنجی نرم‌افزار کنترل','Software and Hardware in the Loop','کنترلر باید با Timing، Quantization، Interface و Failure واقعی پیش از پرواز آزموده شود.','نرم‌افزار بلادرنگ و تست',["MIL الگوریتم، SIL کد تولیدشده، PIL پردازنده و HIL سخت‌افزار/Interface را در حلقه قرار می‌دهد. Fault injection پوشش FDIR را می‌سنجد.","Real-time simulator، Star tracker stimulator، Rate table و Helmholtz cage ابزارهای ADCS هستند. Pass/fail و Traceability باید پیش از آزمون تعریف شود."],[],"کنترلری که در MATLAB پایدار است ممکن است با Delay، Overflow یا Frame mismatch روی Flight computer شکست بخورد.",['MIL','SIL','PIL','HIL','real time','fault injection','rate table']),
// REMOTE SENSING — FOUNDATION
A('rs-spectrum','remote','foundation','طیف الکترومغناطیسی و امضای طیفی','Electromagnetic Spectrum and Spectral Signatures','ماده در طول‌موج‌های مختلف انرژی را جذب، بازتاب یا گسیل می‌کند و این رفتار اطلاعات می‌سازد.','فیزیک نور مقدماتی',["مرئی رنگ، NIR سلامت گیاه، SWIR رطوبت/مواد، TIR دما و Microwave ساختار/زبری/رطوبت را آشکار می‌کند.","Atmospheric windows ناحیه‌هایی با عبور مناسب‌اند. امضای طیفی به جنس، رطوبت، هندسه، جو و تفکیک حسگر وابسته است."],["c=λf"],"گیاه سالم در NIR بازتاب زیاد و در قرمز جذب کلروفیل دارد؛ مبنای شاخص NDVI همین Contrast است.",['electromagnetic spectrum','spectral signature','visible','NIR','SWIR','thermal','microwave']),
A('rs-active-passive','remote','foundation','سنجنده فعال و غیرفعال','Active vs Passive Remote Sensing','Passive انرژی طبیعی را اندازه می‌گیرد؛ Active انرژی می‌فرستد و پاسخ را دریافت می‌کند.','موج و انرژی',["دوربین اپتیکی و Radiometer غیرفعال‌اند و به خورشید یا گسیل حرارتی متکی‌اند. SAR و LiDAR فعال‌اند و زمان/فاز/شدت بازگشت را می‌سنجند.","Active شب کار می‌کند و هندسه را کنترل می‌کند اما توان و پردازش بیشتری می‌خواهد. Microwave از بسیاری ابرها عبور می‌کند ولی تفسیر تصویر متفاوت است."],[],"Sentinel-1 رادار فعال و Sentinel-2 تصویربردار اپتیکی غیرفعال است.",['active sensing','passive sensing','SAR','LiDAR','radiometer']),
A('rs-resolutions','remote','foundation','چهار نوع تفکیک','Spatial, Spectral, Temporal and Radiometric Resolution','کیفیت سنجش فقط اندازه Pixel نیست؛ چهار تفکیک با هم قابلیت استخراج اطلاعات را تعیین می‌کنند.','بدون پیش‌نیاز',["تفکیک مکانی اندازه جزئیات، طیفی تعداد/عرض Band، زمانی Revisit و رادیومتریکی تعداد سطح دیجیتال قابل تشخیص است.","بهبود یک تفکیک ممکن است SNR، Swath، Data volume یا Revisit را بدتر کند. Pixel کوچک الزاماً Resolution واقعی بالا نیست اگر MTF ضعیف باشد."],[],"حسگر ۱۲-bit تا ۴۰۹۶ سطح کد دارد، اما Noise می‌تواند تعداد سطح مؤثر را کمتر کند.",['spatial resolution','spectral resolution','temporal resolution','radiometric resolution']),
A('rs-products','remote','foundation','از اندازه‌گیری تا محصول سنجش‌ازدور','Remote-Sensing Product Chain','داده خام باید Calibration، مکان‌مرجع و پردازش شود تا محصول قابل تصمیم‌گیری ایجاد کند.','تصویر دیجیتال مقدماتی',["Level-0 داده خام سازمان‌یافته؛ Level-1 معمولاً Radiometric/Geometric correction؛ Level-2 پارامتر ژئوفیزیکی؛ Level-3 محصول Gridded/زمانی است. تعریف دقیق هر مأموریت فرق دارد.","Metadata، Quality flag، Projection، Cloud mask و Uncertainty برای استفاده علمی به اندازه تصویر مهم‌اند."],[],"Reflectance سطحی Sentinel-2 محصولی بالاتر از Digital number خام است و برای مقایسه زمانی مناسب‌تر است.",['Level 0','Level 1','Level 2','Level 3','metadata','quality flag']),
// REMOTE — UNIVERSITY
A('rs-radiometry','remote','university','Radiance، Reflectance و قانون پلانک','Radiometry and Planck Law','حسگر Radiance در Aperture و Band مشخص را اندازه می‌گیرد؛ Reflectance و Temperature محصول استنتاجی‌اند.','فیزیک مدرن و انتگرال',["Irradiance توان ورودی بر سطح و Radiance توان بر سطح تصویرشده و Solid angle است. Reflectance نسبت بدون‌بعد وابسته به هندسه است.","قانون پلانک طیف جسم سیاه را می‌دهد؛ Brightness temperature دمای جسم سیاه معادل در Band است و با دمای جنبشی همیشه یکسان نیست."],["Lλ(T)=2hc²/λ⁵ · 1/(e^(hc/λkT)−1)"],"در TIR، Emissivity نامعلوم می‌تواند دمای سطح بازیابی‌شده را Bias کند.",['radiance','irradiance','reflectance','Planck','brightness temperature','emissivity']),
A('rs-imager-design','remote','university','GSD، IFOV، Swath، MTF و SNR','Imager Geometry and Image Quality','هندسه اپتیک و مدار، Sampling و کیفیت واقعی تصویر را با هم تعیین می‌کنند.','اپتیک هندسی و سیگنال',["برای Nadir، GSD تقریباً H·p/f است. IFOV زاویه یک Detector و Swath حاصل FOV کل است. Off-nadir Pixel و Atmospheric path را بدتر می‌کند.","MTF اثر اپتیک، حرکت، Jitter، Detector و پردازش را ترکیب می‌کند. SNR تابع فوتون، Aperture، Exposure، Bandwidth و Noise است."],["GSD≈H p/f","IFOV≈p/f"],"نصف‌کردن GSD با ثابت‌بودن Aperture می‌تواند فوتون هر Pixel و SNR را کاهش دهد.",['GSD','IFOV','FOV','swath','MTF','SNR','aperture','jitter']),
A('rs-calibration','remote','university','کالیبراسیون رادیومتریکی و هندسی','Radiometric and Geometric Calibration','Calibration عدد خام را به کمیت فیزیکی و Pixel را به مختصات زمین متصل می‌کند.','آمار و هندسه',["Dark current، Gain، Nonuniformity و Stray light با Onboard source، Deep space، Sun diffuser یا Vicarious target کنترل می‌شوند.","Geolocation از مدار، Attitude، زمان، مدل Sensor و DEM می‌آید. Orthorectification اثر Relief و Perspective را حذف می‌کند. Ground control point Bias را اصلاح می‌کند."],["L = gain·DN + offset"],"خطای زمان چند میلی‌ثانیه در ماهواره سریع می‌تواند خطای مکانی معنی‌دار ایجاد کند.",['radiometric calibration','geometric correction','orthorectification','GCP','DEM','stray light']),
A('rs-analysis','remote','university','شاخص طیفی، طبقه‌بندی و Change Detection','Spectral Analysis and Classification','ترکیب Bandها ویژگی را تقویت و الگوریتم آن را به کلاس یا تغییر تبدیل می‌کند.','آمار، جبر خطی، پردازش تصویر',["NDVI کنتراست NIR/Red را برای گیاه نشان می‌دهد. PCA بعد را کم و Unmixing سهم Endmemberها را برآورد می‌کند.","Supervised classification به Label و Validation مستقل نیاز دارد. Change detection باید تفاوت فصل، جو، Sensor و Registration را از تغییر واقعی جدا کند."],["NDVI=(NIR−Red)/(NIR+Red)"],"Accuracy کلی بالا با کلاس نادر ضعیف کافی نیست؛ Confusion matrix و F1 هر کلاس بررسی می‌شود.",['NDVI','PCA','classification','change detection','unmixing','confusion matrix']),
// REMOTE — ADVANCED
A('rs-sar','remote','advanced','هندسه SAR و تفکیک Range/Azimuth','Synthetic Aperture Radar Fundamentals','SAR با حرکت پلتفرم Aperture مصنوعی می‌سازد و داده Complex دامنه/فاز را Focus می‌کند.','سیگنال، Fourier، موج، مدار',["Range resolution با Bandwidth و Incidence geometry مرتبط است. Azimuth resolution در Stripmap ایده‌آل از طول آنتن فیزیکی مستقل از Range رفتار می‌کند، اما Processing و Ambiguity قید دارند.","Slant range، Ground range، Layover، Foreshortening و Shadow هندسه تصویر را می‌سازند. Doppler history مکان Target در Azimuth را رمز می‌کند."],["δR_slant=c/(2B)","δR_ground=δR_slant/sinθ"],"کوه رو به Radar ممکن است Layover داشته باشد و قله پیش از دامنه در تصویر دیده شود.",['SAR','range resolution','azimuth resolution','Doppler','layover','shadow','stripmap']),
A('rs-sar-processing','remote','advanced','SAR Focusing، Speckle و Polarimetry','SAR Processing and Polarimetry','داده Raw با Range compression، Azimuth compression و تصحیح حرکت به تصویر Complex تبدیل می‌شود.','DSP، FFT، احتمال',["Range-Doppler، Chirp scaling و Omega-K الگوریتم‌های Focus هستند. Motion compensation خطای مسیر را حذف می‌کند.","Speckle تداخل Coherent است، نه Noise افزوده ساده. Multi-looking/Filter و تحلیل آماری آن را مدیریت می‌کند. Polarimetry ماتریس Scattering و مکانیزم سطح/Double-bounce/Volume را بررسی می‌کند."],[],"فیلتر شدید Speckle ممکن است لبه و Target کوچک را حذف کند؛ کاهش و حفظ اطلاعات Trade است.",['SAR focusing','range Doppler','chirp scaling','omega k','speckle','polarimetry']),
A('rs-insar','remote','advanced','InSAR و اندازه‌گیری تغییرشکل','Interferometric SAR','اختلاف فاز دو مشاهده با هندسه نزدیک، Topography یا جابه‌جایی Line-of-sight را اندازه می‌گیرد.','SAR، فاز، ژئودزی',["Interferogram شامل Flat-earth، Topographic، Deformation، Atmosphere، Orbit error و Noise است. DEM یا زوج‌های متعدد اجزا را جدا می‌کنند.","Phase unwrapping فاز modulo 2π را به میدان پیوسته تبدیل می‌کند. Coherence کیفیت را نشان می‌دهد. PSI/SBAS سری زمانی میلی‌متری را برای Scatterer پایدار استخراج می‌کنند."],["Δφ_defo = −4π d_LOS/λ"],"InSAR فقط مؤلفه جابه‌جایی در راستای دید را می‌سنجد؛ تبدیل به 3D به هندسه‌های صعودی/نزولی و فرض نیاز دارد.",['InSAR','interferogram','phase unwrapping','coherence','PSI','SBAS','deformation']),
A('rs-ai-fusion','remote','advanced','یادگیری عمیق، Data Fusion و عدم‌قطعیت','AI, Data Fusion and Uncertainty','مدل پیشرفته باید Domain shift، Label quality، Resolution mismatch و Uncertainty را مدیریت کند.','یادگیری ماشین، آمار، پردازش تصویر',["CNN/Transformer برای Segmentation، Detection و Retrieval استفاده می‌شوند. Self-supervised learning کمبود Label را کاهش می‌دهد، اما Transfer میان Sensor/فصل/منطقه تضمین‌شده نیست.","Fusion می‌تواند Panchromatic–multispectral، Optical–SAR یا Satellite–ground باشد. Resampling نباید اطلاعات مصنوعی به‌عنوان Resolution واقعی معرفی کند. Calibration احتمال و Out-of-distribution detection برای تصمیم حساس لازم‌اند."],[],"مدلی که روی شهرهای اروپا آموزش دیده ممکن است روی بافت و مصالح شهرهای ایران Bias داشته باشد؛ Validation محلی ضروری است.",['deep learning','transformer','data fusion','domain shift','uncertainty','self supervised','validation'])
];
// COMPLETION SET — one additional topic per level in every domain
window.MADAR_KNOWLEDGE.push(
A('lv-launch-modes','launchers','foundation','پرتاب زمینی، هوایی، دریایی و Responsive Space','Ground, Air, Sea and Responsive Launch','محل و روش پرتاب روی میل قابل دسترس، آب‌وهوا، لجستیک، ایمنی و زمان پاسخ اثر می‌گذارد.','شناخت مقدماتی پرتابگر',["پایگاه زمینی زیرساخت و ظرفیت بالا دارد. Air launch ارتفاع و جابه‌جایی نقطه رهاسازی می‌دهد ولی اندازه پرتابگر را محدود می‌کند. Sea launch امکان انتخاب عرض و مسیر سقوط را بهتر می‌کند ولی عملیات دریایی پیچیده است.","Responsive launch بر آماده‌سازی کوتاه، ذخیره‌پذیری، Mobile ground system و زنجیره تأمین تکرارپذیر تمرکز دارد. پاسخ سریع نباید Qualification و Range safety را حذف کند."],[],"پرتاب هوابرد Pegasus با تغییر محل هواپیما انعطاف Azimuth دارد، ولی ظرفیت آن بسیار کمتر از Heavy-lift زمینی است.",['air launch','sea launch','ground launch','responsive space','mobile launcher']),
A('lv-upper-stage','launchers','university','مرحله بالا، Coast و Restart','Upper Stages, Coast and Restart','مرحله بالا دقت تزریق، چندمداری‌کردن و دفع را با مدیریت سیال و حرارت در خلأ فراهم می‌کند.','پیشرانش و مکانیک مداری',["در Coast، Propellant در بی‌وزنی جابه‌جا می‌شود؛ PMD و Ullage ورودی موتور را پوشش می‌دهند. Igniter، Tank pressure، Battery و Thermal soak باید برای هر Restart آماده باشند.","مرحله چندبارروشن‌شونده می‌تواند Payloadها را به مدارهای متفاوت ببرد. پس از آخرین جدایش، Passivation، Perigee lowering یا Controlled reentry از تولید زباله جلوگیری می‌کند."],["Δv_restart = ∫T/m dt"],"Fregat و Vinci برای مأموریت‌های چند-Burn طراحی شده‌اند؛ Restart ناموفق می‌تواند همه Payloadهای بعدی را در مدار اشتباه رها کند.",['upper stage','restart','ullage','PMD','coast','passivation','multiple payload']),
A('lv-mdo','launchers','advanced','بهینه‌سازی چندرشته‌ای پرتابگر','Multidisciplinary Design Optimization','عملکرد واقعی حاصل Coupling پیشرانش، سازه، آیرودینامیک، حرارت، کنترل، هزینه و Reliability است.','بهینه‌سازی عددی و همه مباحث پرتابگر',["MDO متغیرهایی مانند قطر، فشار محفظه، نسبت انبساط، ضریب سازه، Throttle و مسیر را با تحلیل‌های متصل بهینه می‌کند. Surrogate و Multi-fidelity هزینه محاسبات را کم می‌کنند.","Pareto front نشان می‌دهد کمینه هزینه، بیشینه Payload و بیشینه Reliability یک جواب واحد ندارند. Uncertainty quantification باید Robust design را جایگزین نقطه بهینه شکننده کند."],[],"افزایش قطر Drag و جرم سازه را تغییر می‌دهد، اما حجم مخزن و طول/مود خمشی را نیز بهبود می‌دهد؛ تصمیم را نمی‌توان در یک رشته جدا گرفت.",['MDO','multidisciplinary optimization','Pareto','surrogate','multi fidelity','robust design']),
A('om-escape','orbital','foundation','سرعت فرار، انرژی ویژه و C3','Escape Velocity and C3','خروج از زمین به معنی خاموش‌شدن گرانش نیست؛ انرژی مدار از منفی به صفر یا مثبت می‌رسد.','انرژی و مدار بیضوی',["سرعت فرار محلی √(2μ/r) است. وسیله پس از فرار با سرعت اضافی v∞ نسبت به زمین ادامه می‌دهد. C3 برابر مربع v∞ و شاخص انرژی پرتاب بین‌سیاره‌ای است.","پرتابگر ابتدا اتلاف جو/گرانش و سپس انرژی Hyperbolic را می‌سازد. C3 ظرفیت میان پرتابگرها را بهتر از عبارت مبهم «به مریخ» مقایسه می‌کند."],["v_escape=√(2μ/r)","C3=v∞²"],"C3 صفر مسیر Parabolic ایده‌آل است؛ مأموریت مریخ معمولاً C3 مثبت می‌خواهد.",['escape velocity','C3','hyperbolic excess','v infinity','specific energy']),
A('om-bielliptic-patched','orbital','university','انتقال Bi-elliptic و Patch Conics','Bi-Elliptic Transfers and Patched Conics','هوهمن همیشه کم‌دلتاوی‌ترین انتقال نیست و مأموریت بین‌سیاره‌ای از قطعات دو‌جسمی متصل استفاده می‌کند.','Vis-viva و انتقال هوهمن',["Bi-elliptic با بالا‌بردن Apogee میانی، Plane/energy change را در سرعت کم انجام می‌دهد و برای نسبت شعاع بزرگ می‌تواند از Hohmann ارزان‌تر ولی بسیار کندتر باشد.","Patched conics مسیر خورشیدمرکز را در Sphere of influence به Hyperbola سیاره‌مرکز متصل می‌کند. State و v∞ باید در Patch سازگار باشند."],["r_soi≈a(m/M)^(2/5)"],"انتقال ارزان‌تر با Apogee بسیار بالا ممکن است از نظر زمان، تابش و عملیات نامناسب باشد.",['bi elliptic','patched conics','sphere of influence','interplanetary','v infinity']),
A('om-formation-covariance','orbital','advanced','Formation Flying، Covariance و Conjunction','Formation Flying and Conjunction Assessment','کنترل حرکت نسبی و عدم‌قطعیت برای منظومه نزدیک و اجتناب برخورد حیاتی است.','CW/Hill، احتمال، کنترل',["Relative orbital elements رفتار Formation را بدون تکینگی محلی توصیف می‌کنند. Differential drag، J2 و Maneuver error جدایی را تغییر می‌دهند. کنترل می‌تواند Impulsive یا continuous باشد.","Conjunction assessment Covariance دو جسم را به Encounter plane می‌برد و Probability of collision را با Hard-body radius محاسبه می‌کند. Miss distance به‌تنهایی معیار تصمیم نیست."],["P_rel=P₁+P₂","Pc=∬_HBR N(r;μ,P_rel)dr"],"Covariance بسیار بزرگ می‌تواند Pc را ابتدا افزایش و سپس با پخش احتمال کاهش دهد؛ تفسیر نیازمند هندسه و کیفیت داده است.",['formation flying','relative orbital elements','covariance','conjunction','collision probability','differential drag']),
A('sd-ground-segment','design','foundation','بخش زمینی و طراحی عملیات','Ground Segment and Operations Concept','ماهواره بدون شبکه فرمان، دریافت، پردازش و کاربر نهایی یک مأموریت کامل نیست.','معماری مأموریت',["Ground segment شامل آنتن، RF، Mission control، Flight dynamics، Payload processing، Archive و User delivery است. Availability و Cybersecurity از نیازهای طراحی‌اند.","ConOps زمان AOS/LOS، Command approval، Data latency، Contingency و Staffing را مشخص می‌کند. Autonomy ماهواره به ظرفیت و فاصله تماس Ground وابسته است."],[],"ماهواره تصویربرداری ممکن است سالم باشد، اما اگر Downlink/پردازش داده در زمان موردنیاز کاربر انجام نشود مأموریت عملیاتی شکست خورده است.",['ground segment','mission control','flight dynamics','payload processing','operations concept']),
A('sd-avionics-emc','design','university','رایانه پرواز، Harness و EMC/EMI','Onboard Computer, Harness and EMC','Avionics باید پردازش، زمان، داده و توان را با Interface مقاوم و سازگاری الکترومغناطیسی پیوند دهد.','الکترونیک و سیستم‌های دیجیتال',["انتخاب OBC شامل CPU، حافظه، RTOS، I/O، EDAC، Watchdog و Radiation است. Data busهایی مانند CAN، SpaceWire یا 1553 Trade نرخ، Determinism و پیچیدگی دارند.","Harness جرم و مسیر حرارتی/EMI دارد. Grounding، Shielding، Bonding، Inrush و conducted/radiated emission/susceptibility در EMC plan و آزمون دیده می‌شوند."],[],"رادیوی پرتوان می‌تواند بدون طراحی Ground/Shielding روی Magnetometer یا GPS تداخل ایجاد کند.",['OBC','RTOS','SpaceWire','CAN','harness','EMC','EMI','grounding','shielding']),
A('sd-autonomy-digitaltwin','design','advanced','Autonomy، Digital Twin و Verification Closure','Autonomy and Digital-Twin Verification','خودمختاری پیشرفته باید تصمیم، مدل سلامت و شواهد Verification قابل ردیابی داشته باشد.','MBSE، FDIR، نرم‌افزار بلادرنگ',["Planning onboard، Model-based diagnosis و Reconfiguration زمان پاسخ Ground را کاهش می‌دهند، اما State explosion و رفتار Emergent ریسک‌اند. Rule، model و ML باید Authority روشن داشته باشند.","Digital twin با Telemetry به‌روز می‌شود و برای Prognostics/what-if استفاده می‌گردد. اعتبار مدل، Configuration synchronization و محدوده اعتماد باید مدیریت شود."],[],"مدل ML تشخیص Anomaly بدون پوشش داده خارج از توزیع نباید به‌تنهایی فرمان خاموشی بحرانی بدهد.",['autonomy','digital twin','prognostics','model based diagnosis','verification closure','onboard planning']),
A('ct-modes-safe','control','foundation','حالت‌های کنترل، Detumble و Safe Mode','Control Modes and Safe Mode','کنترل ماهواره مجموعه Mode و Transition است، نه یک کنترلر ثابت برای تمام عمر.','حسگر و عملگر مقدماتی',["پس از جدایش Detumble، سپس Sun acquisition و Normal pointing انجام می‌شود. Slew، Imaging، Downlink، Burn و Safe هرکدام حسگر/عملگر/Gain متفاوت دارند.","Transition guard از ورود ناسازگار جلوگیری می‌کند. Safe mode باید با حداقل سخت‌افزار، توان مثبت و ارتباط کم‌بهره را حفظ کند."],[],"Star tracker ممکن است در Safe mode لازم نباشد؛ Sun sensor و Magnetometer ساده‌تر می‌توانند بقا را تأمین کنند.",['control modes','detumble','safe mode','sun acquisition','mode transition']),
A('ct-magnetic-allocation','control','university','کنترل مغناطیسی و تخصیص عملگر','Magnetic Control and Actuator Allocation','Magnetorquer Torque کامل لحظه‌ای نمی‌دهد و چند عملگر نیازمند تخصیص بهینه فرمان‌اند.','جبر خطی و کنترل',["τ=m×B است؛ مؤلفه موازی B در هر لحظه تولید نمی‌شود. B-dot برای Detumble و Dipole command برای Desaturation استفاده می‌شود.","Control allocation Torque مطلوب را با Pseudoinverse یا Optimization میان Wheel/Thruster/CMG توزیع و Saturation، Failure و محدودیت را رعایت می‌کند."],["τ_mag=m×B","u*=argmin||Bu−τcmd||²"],"سه Magnetorquer متعامد هم در یک لحظه Torque دلخواه سه‌بعدی نمی‌سازند؛ تغییر میدان در طول مدار Controllability زمانی می‌دهد.",['B dot','magnetic control','control allocation','pseudoinverse','actuator saturation']),
A('ct-adaptive-formation','control','advanced','کنترل تطبیقی و Formation Control','Adaptive and Formation Control','عدم‌قطعیت Inertia/محیط و شبکه چندماهواره‌ای به کنترل و تخمین توزیع‌شده نیاز دارند.','Lyapunov، گراف، کنترل غیرخطی',["Adaptive control پارامتر نامعلوم را Online تنظیم می‌کند و با Lyapunov پایداری را اثبات می‌کند؛ Persistent excitation و Projection برای همگرایی/محدودیت مهم‌اند.","Formation control از Graph topology، relative measurements و consensus استفاده می‌کند. Delay، packet loss، collision constraint و Fuel balancing باید در طراحی Distributed دیده شوند."],["u=−Kx−Y(x)θ̂","θ̂̇=−ΓYᵀs"],"Consensus بدون قید Collision می‌تواند مسیر ریاضی همگرا ولی فیزیکی خطرناک تولید کند.",['adaptive control','formation control','consensus','graph theory','distributed control','persistent excitation']),
A('rs-platform-orbit','remote','foundation','انتخاب پلتفرم و مدار سنجش‌ازدور','Remote-Sensing Platforms and Orbits','هواپیما، پهپاد و ماهواره Trade میان پوشش، تفکیک، Revisit و دسترس‌پذیری دارند.','مبانی مدار و تصویر',["Drone تفکیک بالا و پوشش کم؛ هواپیما انعطاف Campaign؛ ماهواره پوشش منظم جهانی می‌دهد. GEO پیوستگی زمانی و LEO/SSO تفکیک و پوشش قطبی فراهم می‌کند.","زمان محلی، زاویه خورشید، Cloud climatology، Incidence و Ground station باید با نوع Payload هماهنگ شوند."],[],"هواشناسی از GEO برای Nowcast و از Polar LEO برای Sounding جهانی دقیق استفاده می‌کند.",['platform','UAV','airborne','SSO','GEO','orbit selection','local time']),
A('rs-atmos-hyper','remote','university','تصحیح جو و تصویربرداری Hyperspectral','Atmospheric Correction and Hyperspectral Imaging','جو سیگنال را جذب و پخش می‌کند؛ Hyperspectral اطلاعات زیاد ولی حساسیت و بعد بالا دارد.','Radiometry و جبر خطی',["تصحیح جو Path radiance، Transmittance، Aerosol و Water vapor را مدل می‌کند. روش Dark-object ساده و Radiative-transfer دقیق‌تر است.","Hyperspectral صدها Band باریک دارد. Continuum removal، Spectral angle، Endmember و Linear/nonlinear unmixing برای شناسایی مواد استفاده می‌شوند."],["L_sensor=L_path+T·L_surface"],"طبقه‌بندی تصویر بدون تصحیح جو ممکن است تفاوت Aerosol دو روز را به تغییر سطح نسبت دهد.",['atmospheric correction','radiative transfer','hyperspectral','endmember','spectral angle','unmixing']),
A('rs-thermal-lidar-altimetry','remote','advanced','سنجش حرارتی، LiDAR و ارتفاع‌سنجی','Thermal, LiDAR and Altimetry','بازیابی دما و ارتفاع نیازمند مدل تابش، زمان‌سنجی دقیق، هندسه و برآورد عدم‌قطعیت است.','Radiometry، احتمال، پردازش سیگنال',["Thermal retrieval Emissivity–temperature separation و Atmospheric correction می‌خواهد. Split-window از دو Band برای کاهش اثر جو استفاده می‌کند.","LiDAR زمان پرواز و Waveform را برای ارتفاع/ساختار؛ Radar/Laser altimeter Range را برای سطح دریا/یخ اندازه می‌گیرد. Orbit error، Tide، wet/dry troposphere و Geoid باید تصحیح شوند."],["R=cΔt/2","σ_T²=J P Jᵀ"],"ارتفاع سطح دریا بدون تصحیح مدار و تأخیر جو نمی‌تواند به تغییر اقلیم چندسانتی‌متری نسبت داده شود.",['thermal remote sensing','LiDAR','altimetry','waveform','split window','uncertainty propagation'])
);
window.MADAR_KNOWLEDGE_SOURCES=[
 {domain:'launchers',name:'NASA Systems Engineering & Launch Vehicle resources',url:'https://ntrs.nasa.gov/'},
 {domain:'orbital',name:'NASA GMAT',url:'https://gmat.atlassian.net/wiki/spaces/GW/'},
 {domain:'design',name:'NASA Small Spacecraft State of the Art',url:'https://www.nasa.gov/smallsat-institute/sst-soa/'},
 {domain:'control',name:'NASA GNC Technical Reports',url:'https://ntrs.nasa.gov/'},
 {domain:'remote',name:'ESA Earth Observation User Guides',url:'https://earth.esa.int/eogateway/'},
 {domain:'remote',name:'NASA Earthdata',url:'https://www.earthdata.nasa.gov/'}
];
})();
