window.MADAR_SATELLITES = {
  types: [
    {
      id:"earth-observation", color:"#72efc6", image:"images/satellites/type-earth-observation.svg",
      title:{fa:"ماهواره سنجش‌ازدور و رصد زمین",en:"Earth-observation satellite"},
      short:{fa:"تصویربرداری و اندازه‌گیری زمین، اقیانوس و جو",en:"Imaging and measuring Earth's land, oceans and atmosphere"},
      description:{fa:"این ماهواره‌ها انرژی بازتابیده یا گسیل‌شده از زمین را در باندهای مرئی، فروسرخ، مایکروویو یا راداری اندازه می‌گیرند. خروجی آن‌ها از تصویر ساده تا پروفایل دما، ارتفاع سطح دریا و تغییرشکل پوسته زمین متغیر است.",en:"These satellites measure reflected or emitted energy from Earth in visible, infrared, microwave or radar bands. Their products range from imagery to atmospheric profiles, sea-surface height and ground deformation."},
      uses:{fa:["کشاورزی و پایش پوشش گیاهی","نقشه‌برداری و مدیریت شهری","پایش سیل، آتش‌سوزی و زلزله","اقلیم، یخ و اقیانوس"],en:["Agriculture and vegetation monitoring","Mapping and urban planning","Flood, fire and earthquake response","Climate, ice and ocean monitoring"]},
      payload:{fa:"دوربین چندطیفی، SAR، ارتفاع‌سنج یا رادیومتر",en:"Multispectral imager, SAR, altimeter or radiometer"},
      orbit:{primary:"SSO / LEO",fa:"معمولاً مدار پایین خورشیدآهنگ در ارتفاع حدود ۵۰۰ تا ۸۰۰ کیلومتر؛ نزدیکی به زمین تفکیک مکانی را بهتر و SSO شرایط روشنایی را تکرارپذیر می‌کند.",en:"Usually a low Sun-synchronous orbit around 500–800 km. Proximity improves spatial resolution and SSO provides repeatable illumination."},
      examples:[{name:"Sentinel-2",orbit:"SSO · 786 km"},{name:"Landsat 9",orbit:"SSO · 705 km"},{name:"Sentinel-1",orbit:"Polar LEO · SAR"}]
    },
    {
      id:"communications", color:"#60cceb", image:"images/satellites/type-communications.svg",
      title:{fa:"ماهواره مخابراتی",en:"Communications satellite"},
      short:{fa:"انتقال صدا، تصویر، اینترنت و داده میان نقاط دور",en:"Relaying voice, video, internet and data across long distances"},
      description:{fa:"محموله مخابراتی سیگنال Uplink را دریافت، فیلتر، تقویت و در Downlink بازپخش می‌کند. معماری می‌تواند Bent-pipe ساده یا پردازش و مسیریابی دیجیتال روی مدار داشته باشد.",en:"A communications payload receives an uplink, filters and amplifies it, then retransmits it on the downlink. Architectures range from bent-pipe repeaters to onboard digital processing and routing."},
      uses:{fa:["تلویزیون و ارتباط ثابت","اینترنت پهن‌باند","ارتباط دریایی و هوایی","رله داده میان ماهواره و زمین"],en:["Broadcast and fixed communications","Broadband internet","Maritime and aviation links","Space-to-ground data relay"]},
      payload:{fa:"ترانسپوندر، آنتن‌های Shape-beam و پردازنده دیجیتال",en:"Transponders, shaped-beam antennas and digital processors"},
      orbit:{primary:"GEO or LEO constellation",fa:"برای پوشش پیوسته یک منطقه، GEO مناسب است؛ برای تأخیر کمتر و پوشش جهانی از منظومه LEO استفاده می‌شود. انتخاب، Trade میان تأخیر، تعداد ماهواره و توان لینک است.",en:"GEO suits continuous regional coverage; LEO constellations provide lower latency and global service. The choice trades latency, satellite count and link power."},
      examples:[{name:"Intelsat / SES",orbit:"GEO · 35,786 km"},{name:"Starlink",orbit:"LEO · ~550 km"},{name:"OneWeb",orbit:"Polar LEO · ~1,200 km"}]
    },
    {
      id:"navigation", color:"#ffc857", image:"images/satellites/type-navigation.svg",
      title:{fa:"ماهواره ناوبری و زمان‌سنجی",en:"Navigation and timing satellite"},
      short:{fa:"تعیین موقعیت، سرعت و زمان دقیق در سراسر جهان",en:"Providing global position, velocity and precise time"},
      description:{fa:"این ماهواره‌ها زمان اتمی و داده مدار دقیق را در سیگنال‌های کدشده پخش می‌کنند. گیرنده با مقایسه زمان رسیدن سیگنال چند ماهواره، Pseudorange و سپس موقعیت و خطای ساعت را حل می‌کند.",en:"These satellites broadcast atomic time and precise orbit data in coded signals. A receiver compares arrival times from multiple satellites to solve pseudoranges, position and clock error."},
      uses:{fa:["ناوبری زمینی، هوایی و دریایی","همگام‌سازی شبکه برق و مخابرات","نقشه‌برداری و ژئودزی","زمان دقیق برای بازار و زیرساخت"],en:["Land, air and maritime navigation","Power-grid and telecom synchronization","Surveying and geodesy","Precise timing for infrastructure"]},
      payload:{fa:"ساعت اتمی، مولد سیگنال ناوبری و آنتن L-band",en:"Atomic clocks, navigation signal generator and L-band antenna"},
      orbit:{primary:"MEO",fa:"اغلب در MEO حدود ۱۹ تا ۲۳ هزار کیلومتر قرار می‌گیرند؛ پوشش وسیع با تعداد متوسط ماهواره و هندسه پایدار جهانی فراهم می‌شود.",en:"Typically placed in MEO around 19,000–23,000 km, balancing wide coverage, constellation size and stable global geometry."},
      examples:[{name:"GPS",orbit:"MEO · 20,200 km"},{name:"Galileo",orbit:"MEO · 23,222 km"},{name:"GLONASS",orbit:"MEO · ~19,100 km"}]
    },
    {
      id:"weather", color:"#9be15d", image:"images/satellites/type-weather.svg",
      title:{fa:"ماهواره هواشناسی",en:"Meteorological satellite"},
      short:{fa:"پایش ابر، دما، رطوبت، باد و رخدادهای شدید",en:"Monitoring clouds, temperature, humidity, winds and severe weather"},
      description:{fa:"هواشناسی فضایی معمولاً دو لایه مکمل دارد: ماهواره GEO برای مشاهده پیوسته رشد طوفان و ماهواره قطبی LEO برای داده جهانی با تفکیک و Sounding بهتر.",en:"Operational meteorology usually combines two layers: GEO satellites continuously watch storm development, while polar LEO satellites provide global, higher-resolution imagery and sounding."},
      uses:{fa:["پیش‌بینی کوتاه‌مدت و هشدار طوفان","مدل عددی هوا","پایش آتش، غبار و آتشفشان","اقلیم و بودجه تابشی"],en:["Nowcasting and storm warning","Numerical weather prediction","Fire, dust and volcano monitoring","Climate and radiation-budget studies"]},
      payload:{fa:"تصویربردار چندطیفی، Sounder فروسرخ و مایکروویو",en:"Multispectral imagers and infrared/microwave sounders"},
      orbit:{primary:"GEO + Polar LEO",fa:"GOES و Meteosat در GEO یک دیسک زمین را پیوسته می‌بینند؛ JPSS و MetOp در مدار قطبی LEO پوشش جهانی دقیق‌تر ایجاد می‌کنند.",en:"GOES and Meteosat use GEO for continuous full-disk views; JPSS and MetOp use polar LEO for detailed global coverage."},
      examples:[{name:"GOES-19",orbit:"GEO · 35,786 km"},{name:"Meteosat",orbit:"GEO"},{name:"MetOp / JPSS",orbit:"Polar LEO · ~820 km"}]
    },
    {
      id:"science", color:"#b9a1ff", image:"images/satellites/type-science.svg",
      title:{fa:"ماهواره علمی و رصدخانه فضایی",en:"Scientific satellite and space observatory"},
      short:{fa:"مطالعه جهان، خورشید، محیط فضا و قوانین بنیادی",en:"Studying the universe, the Sun, the space environment and fundamental physics"},
      description:{fa:"مدار این گروه کاملاً تابع پرسش علمی است. تلسکوپ ممکن است در LEO یا مدار هاله‌ای L2 باشد؛ رصدخانه خورشیدی نزدیک L1 و آزمایش گرانش در مدار بسیار آرام زمین قرار گیرد.",en:"Orbit selection is driven directly by the science question. A telescope may use LEO or an L2 halo orbit; a solar observatory may operate near L1, and gravity missions favor exceptionally quiet Earth orbits."},
      uses:{fa:["اخترفیزیک و کیهان‌شناسی","فیزیک خورشید و هوای فضا","مغناطیس‌سپهر و تابش","آزمایش‌های بنیادی"],en:["Astrophysics and cosmology","Solar physics and space weather","Magnetosphere and radiation","Fundamental-physics experiments"]},
      payload:{fa:"تلسکوپ، طیف‌سنج، آشکارساز ذره یا مغناطیس‌سنج",en:"Telescope, spectrometer, particle detector or magnetometer"},
      orbit:{primary:"Mission-specific: LEO, HEO, L1/L2",fa:"یک مدار ثابت برای علم وجود ندارد: Hubble در LEO، Chandra در HEO، مأموریت‌های خورشیدی در L1 و Webb در مدار هاله‌ای پیرامون L2 کار می‌کنند.",en:"There is no single science orbit: Hubble uses LEO, Chandra uses HEO, solar missions use L1 and Webb operates in a halo orbit around L2."},
      examples:[{name:"Hubble",orbit:"LEO · ~540 km"},{name:"JWST",orbit:"Sun–Earth L2 halo"},{name:"SOHO",orbit:"Sun–Earth L1 halo"}]
    },
    {
      id:"technology", color:"#ff9e64", image:"images/satellites/type-technology.svg",
      title:{fa:"ماهواره نمایش فناوری",en:"Technology-demonstration satellite"},
      short:{fa:"آزمودن سخت‌افزار یا نرم‌افزار جدید پیش از مأموریت عملیاتی",en:"Testing new hardware or software before operational use"},
      description:{fa:"هدف اصلی این ماهواره کاهش ریسک فناوری است. موفقیت ممکن است فقط کارکرد یک پیشران، پردازنده، حسگر یا الگوریتم در محیط واقعی فضا باشد.",en:"The primary goal is technology risk reduction. Success may simply mean operating a new thruster, processor, sensor or algorithm in the real space environment."},
      uses:{fa:["پرواز نخست قطعه جدید","آزمون پردازش هوش مصنوعی روی مدار","نمایش Rendezvous یا Drag sail","کالیبراسیون سطح آمادگی فناوری"],en:["First flight of new hardware","Onboard AI processing tests","Rendezvous or drag-sail demonstrations","Raising technology readiness level"]},
      payload:{fa:"نمونه فناوری یا Hosted payload",en:"Experimental technology or hosted payload"},
      orbit:{primary:"Usually accessible LEO",fa:"اغلب LEO انتخاب می‌شود چون پرتاب ارزان‌تر، تماس زمینی آسان‌تر و دفع پایان عمر ساده‌تر است؛ اما فناوری مقصد ممکن است مدار دیگری را الزام کند.",en:"LEO is common because launch is cheaper, ground contact easier and disposal simpler; however, destination-specific technology may require another environment."},
      examples:[{name:"OPS-SAT",orbit:"LEO"},{name:"PhiSat",orbit:"SSO"},{name:"CubeSat demos",orbit:"LEO rideshare"}]
    },
    {
      id:"security", color:"#ff806f", image:"images/satellites/type-security.svg",
      title:{fa:"ماهواره شناسایی و امنیتی",en:"Reconnaissance and security satellite"},
      short:{fa:"تصویربرداری، هشدار، شنود، پایش دریایی و آگاهی فضایی",en:"Imaging, warning, signals intelligence, maritime surveillance and space awareness"},
      description:{fa:"جزئیات بسیاری از این مأموریت‌ها طبقه‌بندی‌شده است. از نظر مهندسی، نوع محموله می‌تواند اپتیکی، راداری، فروسرخ هشدار زودهنگام یا RF باشد و مدار را تعیین کند.",en:"Many mission details are classified. From an engineering perspective, optical, radar, early-warning infrared or RF payloads drive very different orbit choices."},
      uses:{fa:["تصویربرداری و تغییرات زمینی","هشدار پرتاب و فروسرخ","Signals intelligence","رهگیری اشیای فضایی"],en:["Imaging and change detection","Launch warning and infrared sensing","Signals intelligence","Space-object tracking"]},
      payload:{fa:"اپتیک با دهانه بزرگ، SAR، حسگر IR یا آرایه RF",en:"Large-aperture optics, SAR, infrared sensors or RF arrays"},
      orbit:{primary:"LEO/SSO, GEO or HEO",fa:"تصویربرداری معمولاً LEO/SSO می‌خواهد؛ هشدار پیوسته از GEO یا HEO بهره می‌گیرد و شنود RF بسته به هندسه هدف مدار متفاوت دارد.",en:"Imaging typically favors LEO/SSO; persistent warning uses GEO or HEO, while RF missions select orbit from target geometry."},
      examples:[{name:"Imaging systems",orbit:"LEO / SSO"},{name:"Early warning",orbit:"GEO / HEO"},{name:"Space surveillance",orbit:"Mission-specific"}]
    },
    {
      id:"iot", color:"#5bd6a2", image:"images/satellites/type-iot.svg",
      title:{fa:"ماهواره اینترنت اشیا و جمع‌آوری داده",en:"IoT and data-collection satellite"},
      short:{fa:"دریافت پیام‌های کوتاه از حسگرها، کشتی‌ها، هواپیماها و نقاط دور",en:"Collecting short messages from sensors, ships, aircraft and remote assets"},
      description:{fa:"این ماهواره‌ها حجم پیام کم اما تعداد پایانه بسیار زیاد را مدیریت می‌کنند. Store-and-forward می‌تواند داده را در گذر دریافت و هنگام دسترسی ایستگاه تخلیه کند.",en:"These missions handle small messages from very large terminal populations. Store-and-forward architectures collect data during a pass and downlink it later to a ground station."},
      uses:{fa:["کشاورزی و محیط‌زیست دورافتاده","رهگیری کشتی AIS و هواپیما ADS-B","لجستیک و دارایی‌ها","پیام اضطراری و جست‌وجو و نجات"],en:["Remote agriculture and environment sensing","AIS ship and ADS-B aircraft tracking","Logistics and asset monitoring","Distress messaging and search and rescue"]},
      payload:{fa:"گیرنده باریک‌باند، SDR و پردازش پیام",en:"Narrowband receivers, SDR and message processing"},
      orbit:{primary:"LEO constellation",fa:"LEO توان پایانه زمینی را کم می‌کند و با منظومه چندماهواره‌ای Revisit مناسب می‌دهد. مدار قطبی برای پوشش جهانی و دریایی رایج است.",en:"LEO reduces terminal power and a multi-satellite constellation improves revisit. Polar inclinations are common for global and maritime coverage."},
      examples:[{name:"Iridium services",orbit:"Polar LEO"},{name:"Orbcomm",orbit:"LEO"},{name:"AIS CubeSats",orbit:"Polar LEO"}]
    }
  ],

  components: [
    {id:"payload",n:"01",title:{fa:"محموله مأموریت",en:"Mission payload"},fa:"ابزاری که هدف اصلی ماهواره را انجام می‌دهد؛ دوربین، رادار، ترانسپوندر، ساعت اتمی یا تلسکوپ. جرم، توان، داده و نیاز Pointing آن معماری باس را هدایت می‌کند.",en:"The instrument that performs the primary mission: camera, radar, transponder, atomic clock or telescope. Its mass, power, data and pointing needs drive the bus architecture.",variation:{fa:"در سنجش‌ازدور دوربین رو به زمین است؛ در مخابرات آنتن و ترانسپوندر؛ در ناوبری ساعت اتمی و مولد سیگنال.",en:"Earth observation uses Earth-pointing imagers; communications uses antennas and transponders; navigation uses atomic clocks and signal generators."}},
    {id:"solar",n:"02",title:{fa:"آرایه خورشیدی",en:"Solar arrays"},fa:"تابش خورشید را به توان الکتریکی تبدیل می‌کند. مساحت از توان پایان عمر، دما، زاویه خورشید و تخریب تابشی به دست می‌آید.",en:"Converts sunlight into electrical power. Area is sized from end-of-life demand, temperature, Sun angle and radiation degradation.",variation:{fa:"ماهواره مخابراتی GEO آرایه بزرگ و Sun-tracking دارد؛ CubeSat ممکن است پنل Body-mounted داشته باشد.",en:"GEO communications satellites use large Sun-tracking wings; a CubeSat may rely on body-mounted panels."}},
    {id:"antenna",n:"03",title:{fa:"آنتن‌های مخابراتی",en:"Communications antennas"},fa:"فرمان و تله‌متری را جابه‌جا می‌کنند و داده محموله را می‌فرستند. Gain بیشتر معمولاً Beam باریک‌تر و نیاز Pointing دقیق‌تر دارد.",en:"Carry commands and telemetry and transmit payload data. Higher gain usually means a narrower beam and tighter pointing requirements.",variation:{fa:"GEO ممکن است Reflector چندمتری داشته باشد؛ Safe mode به آنتن کم‌بهره تقریباً همه‌جهته نیاز دارد.",en:"A GEO platform may carry multi-meter reflectors; safe mode needs a robust, near-omnidirectional low-gain antenna."}},
    {id:"computer",n:"04",title:{fa:"رایانه و مدیریت داده",en:"Onboard computer and data handling"},fa:"فرمان‌ها، زمان‌بندی، Modeها، ذخیره داده، FDIR و ارتباط میان زیرسامانه‌ها را مدیریت می‌کند.",en:"Manages commands, timing, modes, data storage, FDIR and communication among subsystems.",variation:{fa:"مأموریت تصویربرداری حافظه پرظرفیت می‌خواهد؛ نمایش فناوری ممکن است پردازنده AI مقاوم به تابش را آزمایش کند.",en:"Imaging missions need large storage; technology demos may test radiation-tolerant AI processors."}},
    {id:"adcs",n:"05",title:{fa:"حسگرهای تعیین وضعیت",en:"Attitude-determination sensors"},fa:"Star tracker، ژیروسکوپ، حسگر خورشید و مغناطیس‌سنج نگرش و نرخ زاویه‌ای را تخمین می‌زنند.",en:"Star trackers, gyros, Sun sensors and magnetometers estimate attitude and angular rate.",variation:{fa:"تلسکوپ و دوربین تفکیک‌بالا Star tracker دقیق و Jitter کم می‌خواهند؛ IoT ممکن است کنترل ساده‌تری داشته باشد.",en:"Telescopes and high-resolution imagers require precise star tracking and low jitter; IoT missions may accept simpler control."}},
    {id:"wheels",n:"06",title:{fa:"چرخ عکس‌العملی و عملگرها",en:"Reaction wheels and actuators"},fa:"با تبادل مومنتوم، ماهواره را می‌چرخاند و ثابت نگه می‌دارد. Magnetorquer یا Thruster اشباع مومنتوم را تخلیه می‌کند.",en:"Rotate and stabilize the spacecraft by exchanging angular momentum. Magnetorquers or thrusters unload accumulated momentum.",variation:{fa:"رصدخانه علمی کنترل بسیار نرم می‌خواهد؛ ماهواره Spin-stabilized ممکن است اصلاً چرخ سه‌محوره نداشته باشد.",en:"Science observatories demand very smooth control; a spin-stabilized spacecraft may not use a three-axis wheel set."}},
    {id:"power",n:"07",title:{fa:"واحد توان و باتری",en:"Power conditioning and batteries"},fa:"توان آرایه را تنظیم، باتری را شارژ و انرژی را میان بارها توزیع و حفاظت می‌کند. باتری عملیات Eclipse را پوشش می‌دهد.",en:"Conditions array power, charges batteries, distributes energy and protects loads. Batteries support operations through eclipse.",variation:{fa:"SAR هنگام تصویربرداری Peak power بزرگی دارد؛ Safe mode باید با کمترین توان زنده بماند.",en:"SAR imaging creates high peak power; safe mode must remain alive at minimum consumption."}},
    {id:"thermal",n:"08",title:{fa:"رادیاتور و کنترل حرارت",en:"Radiators and thermal control"},fa:"با رادیاتور، پوشش، MLI، Heat pipe و Heater دما را در محدوده عملیاتی نگه می‌دارد.",en:"Uses radiators, coatings, MLI, heat pipes and heaters to maintain operational temperatures.",variation:{fa:"آشکارساز فروسرخ ممکن است Cryocooler بخواهد؛ CubeSat معمولاً بیشتر به راهکار Passive متکی است.",en:"Infrared detectors may require cryocoolers; CubeSats rely more heavily on passive control."}},
    {id:"propulsion",n:"09",title:{fa:"سامانه پیشرانش",en:"Propulsion system"},fa:"برای اصلاح مدار، Station keeping، اجتناب از برخورد و دفع پایان عمر دلتاوی تولید می‌کند.",en:"Provides delta-v for orbit correction, station keeping, collision avoidance and end-of-life disposal.",variation:{fa:"GEO موتور اوج و Station keeping دارد؛ LEO کوچک ممکن است بدون پیشران یا با Hall/Resistojet باشد.",en:"GEO spacecraft use apogee and station-keeping propulsion; a small LEO craft may be propulsion-free or use Hall/resistojet systems."}},
    {id:"structure",n:"10",title:{fa:"سازه و رابط پرتابگر",en:"Structure and launcher interface"},fa:"بارهای پرتاب را تحمل، تجهیزات را نگه‌داری و مسیر مکانیکی و حرارتی ایجاد می‌کند. حلقه پایین به Adapter پرتابگر متصل می‌شود.",en:"Carries launch loads, supports equipment and provides mechanical and thermal paths. The lower ring attaches to the launch-vehicle adapter.",variation:{fa:"دهانه تلسکوپ پایداری ابعادی می‌خواهد؛ ماهواره مخابراتی سازه‌های Deployable بزرگ دارد.",en:"Telescope structures demand dimensional stability; communications platforms carry large deployable structures."}}
  ],

  missionProfiles: {
    imaging:{type:"earth-observation",title:{fa:"تصویربرداری اپتیکی زمین",en:"Optical Earth imaging"},orbit:"SSO · 500–800 km",why:{fa:"فاصله کم برای تفکیک و زمان محلی تقریباً ثابت برای نور مشابه.",en:"Low altitude supports resolution and fixed local solar time gives comparable illumination."},example:"Sentinel-2 · 786 km"},
    radar:{type:"earth-observation",title:{fa:"رادار دهانه مصنوعی",en:"Synthetic-aperture radar"},orbit:"Polar/SSO LEO · 500–800 km",why:{fa:"رادار شب و روز و از میان ابر کار می‌کند؛ LEO بودجه توان و تفکیک را عملی نگه می‌دارد.",en:"Radar works day/night and through clouds; LEO keeps power and resolution practical."},example:"Sentinel-1 · Polar LEO"},
    broadcast:{type:"communications",title:{fa:"پخش تلویزیونی و ارتباط ثابت",en:"Broadcast and fixed communications"},orbit:"GEO · 35,786 km",why:{fa:"پوشش دائمی یک منطقه و آنتن زمینی ثابت.",en:"Continuous regional coverage with fixed ground antennas."},example:"Intelsat / SES · GEO"},
    broadband:{type:"communications",title:{fa:"اینترنت کم‌تأخیر جهانی",en:"Low-latency global broadband"},orbit:"LEO constellation · 500–1,200 km",why:{fa:"فاصله کم تأخیر را کاهش می‌دهد؛ برای پوشش پیوسته تعداد زیادی ماهواره لازم است.",en:"Short range lowers latency, but continuous coverage requires many satellites."},example:"Starlink / OneWeb"},
    navigation:{type:"navigation",title:{fa:"ناوبری جهانی",en:"Global navigation"},orbit:"MEO · ~20,000–23,000 km",why:{fa:"هر ماهواره سطح بزرگی را می‌پوشاند و منظومه با تعداد متوسط هندسه جهانی ایجاد می‌کند.",en:"Each satellite covers a wide area and a moderate constellation provides global geometry."},example:"GPS · 20,200 km"},
    nowcast:{type:"weather",title:{fa:"هشدار سریع هواشناسی",en:"Weather nowcasting"},orbit:"GEO",why:{fa:"مشاهده پیوسته رشد ابر و طوفان بر یک نیم‌کره.",en:"Persistent observation of cloud and storm evolution over a hemisphere."},example:"GOES-19 · GEO"},
    astronomy:{type:"science",title:{fa:"رصد فروسرخ جهان عمیق",en:"Deep-universe infrared astronomy"},orbit:"Sun–Earth L2 halo",why:{fa:"محیط حرارتی پایدار و قرارگیری خورشید، زمین و ماه در یک سمت برای Shielding.",en:"Stable thermal geometry keeps Sun, Earth and Moon on one side for shielding."},example:"JWST · L2 halo"},
    iot:{type:"iot",title:{fa:"دریافت پیام حسگرهای دورافتاده",en:"Remote sensor messaging"},orbit:"Polar LEO constellation",why:{fa:"توان کم پایانه، پوشش جهانی و Revisit مناسب با چند ماهواره.",en:"Low terminal power, global reach and useful revisit from a constellation."},example:"Orbcomm / AIS CubeSats"}
  },

  architectures:[
    {id:"sentinel2",name:"Sentinel-2 class",agency:"ESA / Copernicus",image:"images/satellites/type-earth-observation.svg",type:{fa:"سنجش‌ازدور اپتیکی",en:"Optical Earth observation"},mass:"1,140 kg",power:"~1.7 kW",orbit:"SSO · 786 km",lifetime:"7+ years",payload:{fa:"تصویربردار چندطیفی ۱۳ باند",en:"13-band multispectral imager"},attitude:{fa:"سه‌محوره؛ Star tracker و ژیروسکوپ فیبر نوری",en:"Three-axis; star tracker and fiber-optic gyro"},comms:"X-band payload · S-band TT&C",propulsion:{fa:"هیدرازین برای نگهداری مدار",en:"Hydrazine orbit maintenance"},data:"560 Mbit/s · 2.4 Tbit storage",strength:{fa:"تصویر جهانی تکرارپذیر و Wide swath",en:"Repeatable global imagery and wide swath"},constraint:{fa:"ابر برای اپتیک و حجم داده بسیار بالا",en:"Cloud obstruction and very high data volume"},metrics:{mass:1140,power:1700,lifetime:7,dataRate:560,altitude:786},source:"https://www.esa.int/Enabling_Support/Operations/Sentinel-2_operations"},
    {id:"galileo",name:"Galileo FOC",agency:"ESA / EU",image:"images/satellites/type-navigation.svg",type:{fa:"ناوبری و زمان‌سنجی",en:"Navigation and timing"},mass:"~715 kg",power:"~1.9 kW",orbit:"MEO · 23,222 km",lifetime:"12 years",payload:{fa:"چهار ساعت اتمی و مولد سیگنال ناوبری",en:"Four atomic clocks and navigation signal generator"},attitude:{fa:"سه‌محوره؛ حسگر زمین/خورشید و چرخ",en:"Three-axis; Earth/Sun sensors and wheels"},comms:"L-band service · C/S-band control",propulsion:{fa:"پیشرانش شیمیایی برای کنترل مدار",en:"Chemical orbit-control propulsion"},data:{fa:"پخش پیوسته سیگنال زمان و Ephemeris",en:"Continuous timing and ephemeris broadcast"},strength:{fa:"زمان بسیار پایدار و پوشش جهانی منظومه‌ای",en:"Ultra-stable timing and global constellation coverage"},constraint:{fa:"محیط تابشی MEO و نیاز Redundancy ساعت",en:"MEO radiation and clock redundancy needs"},metrics:{mass:715,power:1900,lifetime:12,dataRate:50,altitude:23222},source:"https://www.esa.int/Applications/Satellite_navigation/Galileo/Satellite_anatomy"},
    {id:"geo-comms",name:"GEO communications class",agency:"Commercial reference",image:"images/satellites/type-communications.svg",type:{fa:"مخابرات پهن‌باند زمین‌ایستا",en:"Geostationary broadband communications"},mass:"2,500–6,000 kg",power:"10–25 kW class",orbit:"GEO · 35,786 km",lifetime:"15+ years",payload:{fa:"ترانسپوندر/پردازنده دیجیتال و آنتن‌های Shape-beam",en:"Transponders/digital processor and shaped-beam antennas"},attitude:{fa:"سه‌محوره با Pointing دقیق آنتن",en:"Three-axis with precise antenna pointing"},comms:"Ku/Ka/C-band high-throughput links",propulsion:{fa:"موتور اوج یا Electric orbit raising و Station keeping",en:"Apogee/electric orbit raising and station keeping"},data:{fa:"ظرفیت چندده تا چندصد Gbit/s",en:"Tens to hundreds of Gbit/s capacity"},strength:{fa:"پوشش پیوسته منطقه و پایانه ثابت",en:"Persistent regional coverage and fixed terminals"},constraint:{fa:"تأخیر زیاد، توان/جرم بالا و محدودیت Slot",en:"High latency, power/mass and orbital-slot constraints"},metrics:{mass:4500,power:18000,lifetime:15,dataRate:100000,altitude:35786},source:"https://www.esa.int/Applications/Connectivity_and_Secure_Communications/Hylas/Platform"},
    {id:"cubesat6u",name:"6U CubeSat reference",agency:"Educational reference",image:"images/satellites/type-technology.svg",type:{fa:"نمایش فناوری کوچک",en:"Small technology demonstrator"},mass:"~8–12 kg",power:"20–80 W class",orbit:"LEO · 400–600 km",lifetime:"1–3 years",payload:{fa:"نمونه فناوری، دوربین کوچک یا SDR",en:"Technology experiment, small imager or SDR"},attitude:{fa:"چرخ/مگنتورکر کوچک؛ دقت متوسط",en:"Small wheels/magnetorquers; moderate precision"},comms:"UHF/VHF or S/X-band",propulsion:{fa:"اختیاری؛ Cold gas، Resistojet یا بدون پیشران",en:"Optional cold gas/resistojet or none"},data:{fa:"محدود به توان و گذر ایستگاه",en:"Limited by power and ground passes"},strength:{fa:"هزینه و زمان توسعه کمتر",en:"Lower cost and shorter development"},constraint:{fa:"توان، دهانه، حرارت، Pointing و Downlink محدود",en:"Limited power, aperture, thermal control, pointing and downlink"},metrics:{mass:10,power:50,lifetime:2,dataRate:2,altitude:500},source:"https://www.esa.int/Enabling_Support/Preparing_for_the_Future/Discovery_and_Preparation/CubeSats"},
    {id:"jwst",name:"James Webb Space Telescope",agency:"NASA / ESA / CSA",image:"images/satellites/type-science.svg",type:{fa:"رصدخانه فروسرخ بزرگ",en:"Large infrared observatory"},mass:"~6,200 kg",power:"~2 kW",orbit:"Sun–Earth L2 halo",lifetime:"10+ years",payload:{fa:"آینه ۶.۵ متری و چهار ابزار علمی فروسرخ",en:"6.5 m mirror and four infrared science instruments"},attitude:{fa:"سه‌محوره بسیار دقیق با Fine Guidance Sensor",en:"Ultra-precise three-axis control with Fine Guidance Sensor"},comms:"Ka-band science · S-band TT&C",propulsion:{fa:"اصلاح مسیر، Halo maintenance و Momentum unloading",en:"Trajectory correction, halo maintenance and momentum unloading"},data:"~28 Mbit/s science downlink",strength:{fa:"حساسیت فروسرخ و محیط حرارتی سرد",en:"Infrared sensitivity and cold thermal environment"},constraint:{fa:"استقرار بسیار پیچیده و نبود سرویس ساده",en:"Highly complex deployment and no simple servicing"},metrics:{mass:6200,power:2000,lifetime:10,dataRate:28,altitude:1500000},source:"https://science.nasa.gov/mission/webb/spacecraftoverview/"},
    {id:"goesr",name:"GOES-R class",agency:"NASA / NOAA",image:"images/satellites/type-weather.svg",type:{fa:"هواشناسی زمین‌ایستا",en:"Geostationary meteorology"},mass:"~5,200 kg launch",power:"~4 kW class",orbit:"GEO · 35,786 km",lifetime:"10+ years",payload:{fa:"ABI، نقشه‌بردار صاعقه و ابزار هوای فضا",en:"ABI, lightning mapper and space-weather instruments"},attitude:{fa:"سه‌محوره برای مشاهده پیوسته دیسک زمین",en:"Three-axis for continuous full-disk viewing"},comms:{fa:"Downlink داده محیطی و رله هشدار",en:"Environmental data downlink and alert relay"},propulsion:{fa:"تکمیل GEO و Station keeping",en:"GEO insertion completion and station keeping"},data:{fa:"جریان پیوسته تصویر و Sounding",en:"Continuous imaging and sounding stream"},strength:{fa:"پایش تقریباً بلادرنگ طوفان",en:"Near-real-time severe-weather monitoring"},constraint:{fa:"تفکیک ضعیف‌تر نسبت به LEO و پوشش قطبی محدود",en:"Lower resolution than LEO and weak polar coverage"},metrics:{mass:5200,power:4000,lifetime:10,dataRate:100,altitude:35786},source:"https://www.nesdis.noaa.gov/about/k-12-education/satellites-technology/meet-goes-r-series-weather-satellite"}
  ],

  sources:[
    {name:"ESA Satellite Anatomy",url:"https://www.esa.int/Applications/Satellite_navigation/Galileo/Satellite_anatomy"},
    {name:"NASA Spacecraft Bus",url:"https://science.nasa.gov/mission/webb/spacecraftoverview/"},
    {name:"ESA Types of Orbits",url:"https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits"},
    {name:"GPS Space Segment",url:"https://www.gps.gov/space-segment"},
    {name:"NOAA Geostationary and Polar Weather",url:"https://www.nesdis.noaa.gov/news/how-noaa-satellites-help-us-stay-ahead-of-severe-weather-season"},
    {name:"ESA Sentinel-2 Operations",url:"https://www.esa.int/Enabling_Support/Operations/Sentinel-2_operations"}
  ]
};

window.MADAR_DATA?.sources?.push(
  {name:"Satellite Anatomy",org:"ESA Galileo",type:"اجزای ماهواره",lang:"EN",trust:"رسمی",url:"https://www.esa.int/Applications/Satellite_navigation/Galileo/Satellite_anatomy",note:"شرح رسمی آنتن‌ها، ساعت اتمی، حسگرها، چرخ‌های عکس‌العملی، کنترل توان، رایانه و رادیاتورهای ماهواره Galileo."},
  {name:"Spacecraft Bus",org:"NASA Webb",type:"زیرسامانه‌های فضاپیما",lang:"EN",trust:"رسمی",url:"https://science.nasa.gov/mission/webb/spacecraftoverview/",note:"معرفی شش زیرسامانه اصلی باس فضاپیما: توان، کنترل وضعیت، مخابرات، C&DH، پیشرانش و حرارت."},
  {name:"GPS Space Segment",org:"GPS.gov",type:"مدار ناوبری",lang:"EN",trust:"رسمی",url:"https://www.gps.gov/space-segment",note:"چیدمان منظومه GPS در مدار MEO با ارتفاع تقریبی ۲۰٬۲۰۰ کیلومتر و دو گردش در روز."},
  {name:"GOES and JPSS",org:"NOAA NESDIS",type:"ماهواره هواشناسی",lang:"EN",trust:"رسمی",url:"https://www.nesdis.noaa.gov/news/how-noaa-satellites-help-us-stay-ahead-of-severe-weather-season",note:"نقش مکمل ماهواره‌های GEO برای پایش پیوسته و ماهواره‌های قطبی LEO برای داده جهانی دقیق‌تر."},
  {name:"Sentinel-2 Operations",org:"ESA / Copernicus",type:"رصد زمین و SSO",lang:"EN",trust:"رسمی",url:"https://www.esa.int/Enabling_Support/Operations/Sentinel-2_operations",note:"مأموریت رصد زمین Sentinel-2 در مدار خورشیدآهنگ ۷۸۶ کیلومتری و ویژگی‌های Payload، AOCS و Downlink."},
  {name:"NASA Official RSS",org:"NASA",type:"انتشار برخط",lang:"EN",trust:"رسمی/زنده",url:"https://www.nasa.gov/news-release/feed/",note:"Feed رسمی مطالب تازه NASA؛ برنامه آن را هر سه دقیقه بررسی و عنوان/خلاصه فارسی را کنار متن اصلی ذخیره می‌کند."},
  {name:"ESA Top News RSS",org:"European Space Agency",type:"انتشار برخط",lang:"EN",trust:"رسمی/زنده",url:"https://www.esa.int/rssfeed/TopNews",note:"Feed رسمی Top News آژانس فضایی اروپا برای همگام‌سازی نزدیک به زمان انتشار."}
);
